# Ruby's standard library, the half its Ruby does not write: methods compiled
# into an extension (`Pathname#read`, `Digest::Class.hexdigest`), as RBS
# describes them. Generated by `script/stdlib_sigs.rb` from rbs 3.8.0 and Ruby 3.4.9's
# stdlib; do not edit by hand (DEC-220).
#
# Served only when a checkout's stdlib is indexed, one file per top-level
# owner, and every method is a declaration. A class is declared here only
# when no Ruby file declares it (`Digest::SHA256`); only then do its
# superclass and mixins here count.

class Addrinfo
  sig { returns(::Array) }
  def self.getaddrinfo(nodename, service = nil, family = nil, socktype = nil, protocol = nil, flags = nil)
  end

  sig { returns(::Addrinfo) }
  def self.ip(host)
  end

  sig { returns(::Addrinfo) }
  def self.tcp(host, port)
  end

  sig { returns(::Addrinfo) }
  def self.udp(host, port)
  end

  sig { returns(::Addrinfo) }
  def self.unix(path, socktype = nil)
  end

  sig { returns(::Integer) }
  def afamily
  end

  sig { returns(::String) }
  def canonname
  end

  def getnameinfo(flags = nil)
  end

  sig { returns(::String) }
  def inspect
  end

  sig { returns(::String) }
  def inspect_sockaddr
  end

  def ip?
  end

  sig { returns(::String) }
  def ip_address
  end

  sig { returns(::Integer) }
  def ip_port
  end

  def ip_unpack
  end

  def ipv4?
  end

  def ipv4_loopback?
  end

  def ipv4_multicast?
  end

  def ipv4_private?
  end

  def ipv6?
  end

  def ipv6_linklocal?
  end

  def ipv6_loopback?
  end

  def ipv6_mc_global?
  end

  def ipv6_mc_linklocal?
  end

  def ipv6_mc_nodelocal?
  end

  def ipv6_mc_orglocal?
  end

  def ipv6_mc_sitelocal?
  end

  def ipv6_multicast?
  end

  def ipv6_sitelocal?
  end

  def ipv6_to_ipv4
  end

  def ipv6_unique_local?
  end

  def ipv6_unspecified?
  end

  def ipv6_v4compat?
  end

  def ipv6_v4mapped?
  end

  sig { returns(::String) }
  def marshal_dump
  end

  def marshal_load(arg1)
  end

  sig { returns(::Integer) }
  def pfamily
  end

  sig { returns(::Integer) }
  def protocol
  end

  sig { returns(::Integer) }
  def socktype
  end

  sig { returns(::String) }
  def to_s
  end

  sig { returns(::String) }
  def to_sockaddr
  end

  def unix?
  end

  sig { returns(::String) }
  def unix_path
  end
end

class BasicSocket < ::IO
  def self.do_not_reverse_lookup
  end

  def self.do_not_reverse_lookup=(arg1)
  end

  def self.for_fd(fd)
  end

  def close_read
  end

  def close_write
  end

  def do_not_reverse_lookup
  end

  def do_not_reverse_lookup=(arg1)
  end

  def getpeereid
  end

  sig { returns(::String) }
  def getpeername
  end

  sig { returns(::String) }
  def getsockname
  end

  def getsockopt(level, optname)
  end

  sig { returns(::Addrinfo) }
  def local_address
  end

  sig { returns(::String) }
  def recv(maxlen, flags = nil, outbuf = nil)
  end

  sig { returns(::Addrinfo) }
  def remote_address
  end

  def send(msg, flags = nil, dest_sockaddr = nil)
  end

  def setsockopt(level = nil, optname = nil, optval = nil, *args)
  end

  def shutdown(flags)
  end

  private
  def __recv_nonblock(arg1, arg2, arg3, arg4)
  end

  def __recvmsg(arg1, arg2, arg3, arg4)
  end

  def __recvmsg_nonblock(arg1, arg2, arg3, arg4, arg5)
  end

  def __sendmsg(arg1, arg2, arg3, arg4)
  end

  def __sendmsg_nonblock(arg1, arg2, arg3, arg4, arg5)
  end
end

module Benchmark
  class Job
  end

  class Report
  end

  class Tms
  end
end

class CGI
  include ::CGI::Util
  include ::CGI::Escape

  class Cookie < ::Array
  end

  module Escape
    sig { returns(::String) }
    def escape(string)
    end

    sig { returns(::String) }
    def escapeHTML(string)
    end

    sig { returns(::String) }
    def escapeURIComponent(string)
    end

    sig { returns(::String) }
    def unescape(string, encoding = nil)
    end

    sig { returns(::String) }
    def unescapeHTML(string)
    end

    sig { returns(::String) }
    def unescapeURIComponent(string, encoding = nil)
    end
  end

  class InvalidEncoding < ::Exception
  end

  module QueryExtension
  end

  module Util
    include ::CGI::Escape

    sig { returns(::String) }
    def escape_html(str)
    end

    sig { returns(::String) }
    def h(str)
    end

    sig { returns(::String) }
    def unescape_html(str)
    end
  end
end

module Coverage
  sig { returns(::Hash) }
  def self.peek_result
  end

  sig { returns(::Hash) }
  def self.result(stop: true, clear: true)
  end

  def self.resume
  end

  def self.running?
  end

  def self.setup(arg1 = nil, lines: nil, branches: nil, methods: nil, eval: nil, oneshot_lines: true)
  end

  def self.start(*args)
  end

  def self.state
  end

  def self.supported?(mode)
  end

  def self.suspend
  end
end

class Date
  include ::Comparable

  sig { returns(::Hash) }
  def self._httpdate(string, limit: 128)
  end

  sig { returns(::Hash) }
  def self._iso8601(string, limit: 128)
  end

  sig { returns(::Hash) }
  def self._jisx0301(string, limit: 128)
  end

  sig { returns(::Hash) }
  def self._parse(string, comp = true, limit: 128)
  end

  sig { returns(::Hash) }
  def self._rfc2822(string, limit: 128)
  end

  sig { returns(::Hash) }
  def self._rfc3339(string, limit: 128)
  end

  sig { returns(::Hash) }
  def self._rfc822(str)
  end

  sig { returns(::Hash) }
  def self._strptime(string, format = '%F')
  end

  sig { returns(::Hash) }
  def self._xmlschema(string, limit: 128)
  end

  def self.civil(*args)
  end

  def self.commercial(cwyear = -4712, cweek = 1, cwday = 1, start = Date::ITALY)
  end

  def self.gregorian_leap?(year)
  end

  def self.httpdate(str, start = nil)
  end

  def self.iso8601(string, start = Date::ITALY, limit: 128)
  end

  def self.jd(jd, start = Date::ITALY)
  end

  def self.jisx0301(string, start = Date::ITALY, limit: 128)
  end

  def self.julian_leap?(year)
  end

  def self.leap?(year)
  end

  def self.ordinal(year = -4712, yday = 1, start = Date::ITALY)
  end

  def self.parse(string = '-4712-01-01', comp = true, start = Date::ITALY, limit: 128)
  end

  def self.rfc2822(str, start = nil)
  end

  def self.rfc3339(string, start = Date::ITALY, limit: 128)
  end

  def self.rfc822(str, start = nil)
  end

  def self.strptime(string, format = '%F', start = Date::ITALY)
  end

  def self.today(start = Date::ITALY)
  end

  def self.valid_civil?(year, month, mday, start = Date::ITALY)
  end

  def self.valid_commercial?(cwyear, cweek, cwday, start = Date::ITALY)
  end

  def self.valid_date?(year, month, mday, start = nil)
  end

  def self.valid_jd?(jd, start = Date::ITALY)
  end

  def self.valid_ordinal?(year, yday, start = Date::ITALY)
  end

  def self.xmlschema(string, start = Date::ITALY, limit: 128)
  end

  def +(arg1)
  end

  def -(arg1)
  end

  def <<(arg1)
  end

  def <=>(arg1)
  end

  def ===(arg1)
  end

  def >>(arg1)
  end

  sig { returns(::Rational) }
  def ajd
  end

  sig { returns(::Rational) }
  def amjd
  end

  sig { returns(::String) }
  def asctime
  end

  sig { returns(::String) }
  def ctime
  end

  sig { returns(::Integer) }
  def cwday
  end

  sig { returns(::Integer) }
  def cweek
  end

  sig { returns(::Integer) }
  def cwyear
  end

  sig { returns(::Integer) }
  def day
  end

  sig { returns(::Hash) }
  def deconstruct_keys(array_of_names_or_nil)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def downto(min, &block)
  end

  def england
  end

  def friday?
  end

  def gregorian
  end

  def gregorian?
  end

  sig { returns(::String) }
  def httpdate
  end

  sig { returns(::String) }
  def inspect
  end

  sig { returns(::String) }
  def iso8601
  end

  def italy
  end

  sig { returns(::Integer) }
  def jd
  end

  sig { returns(::String) }
  def jisx0301
  end

  def julian
  end

  def julian?
  end

  sig { returns(::Integer) }
  def ld
  end

  def leap?
  end

  sig { returns(::Integer) }
  def mday
  end

  sig { returns(::Integer) }
  def mjd
  end

  sig { returns(::Integer) }
  def mon
  end

  def monday?
  end

  sig { returns(::Integer) }
  def month
  end

  def new_start(start = nil)
  end

  def next
  end

  def next_day(n = 1)
  end

  def next_month(n = 1)
  end

  def next_year(n = 1)
  end

  def prev_day(n = 1)
  end

  def prev_month(n = 1)
  end

  def prev_year(n = 1)
  end

  sig { returns(::String) }
  def rfc2822
  end

  sig { returns(::String) }
  def rfc3339
  end

  sig { returns(::String) }
  def rfc822
  end

  def saturday?
  end

  sig { returns(::Float) }
  def start
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def step(limit, step = 1, &block)
  end

  sig { returns(::String) }
  def strftime(format = '%F')
  end

  def succ
  end

  def sunday?
  end

  def thursday?
  end

  def to_date
  end

  sig { returns(::DateTime) }
  def to_datetime
  end

  sig { returns(::String) }
  def to_s
  end

  sig { returns(::Time) }
  def to_time
  end

  def tuesday?
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def upto(max, &block)
  end

  sig { returns(::Integer) }
  def wday
  end

  def wednesday?
  end

  sig { returns(::String) }
  def xmlschema
  end

  sig { returns(::Integer) }
  def yday
  end

  sig { returns(::Integer) }
  def year
  end
end

class DateTime < ::Date
  sig { returns(::Hash) }
  def self._strptime(str, format = nil)
  end

  sig { returns(::DateTime) }
  def self.civil(*args)
  end

  sig { returns(::DateTime) }
  def self.commercial(cwyear = nil, cweek = nil, cwday = nil, hour = nil, minute = nil, second = nil, offset = nil, start = nil)
  end

  sig { returns(::DateTime) }
  def self.httpdate(str, start = nil)
  end

  sig { returns(::DateTime) }
  def self.iso8601(string, start = nil, limit: 128)
  end

  sig { returns(::DateTime) }
  def self.jd(jd = nil, hour = nil, minute = nil, second = nil, offset = nil, start = nil)
  end

  sig { returns(::DateTime) }
  def self.jisx0301(string, start = nil, limit: 128)
  end

  sig { returns(::DateTime) }
  def self.new(*args)
  end

  sig { returns(::DateTime) }
  def self.now(start = nil)
  end

  sig { returns(::DateTime) }
  def self.ordinal(year = nil, yday = nil, hour = nil, minute = nil, second = nil, offset = nil, start = nil)
  end

  sig { returns(::DateTime) }
  def self.parse(string, complete = nil, start = nil, limit: 128)
  end

  sig { returns(::DateTime) }
  def self.rfc2822(str, start = nil)
  end

  sig { returns(::DateTime) }
  def self.rfc3339(string, start = nil, limit: 128)
  end

  sig { returns(::DateTime) }
  def self.rfc822(str, start = nil)
  end

  sig { returns(::DateTime) }
  def self.strptime(str, format = nil, start = nil)
  end

  sig { returns(::DateTime) }
  def self.xmlschema(string, start = nil, limit: 128)
  end

  sig { returns(::Hash) }
  def deconstruct_keys(array_of_names_or_nil)
  end

  sig { returns(::Integer) }
  def hour
  end

  sig { returns(::String) }
  def iso8601(n = nil)
  end

  sig { returns(::String) }
  def jisx0301(n = nil)
  end

  sig { returns(::Integer) }
  def min
  end

  sig { returns(::Integer) }
  def minute
  end

  sig { returns(::DateTime) }
  def new_offset(offset = nil)
  end

  sig { returns(::Rational) }
  def offset
  end

  sig { returns(::String) }
  def rfc3339(n = nil)
  end

  sig { returns(::Integer) }
  def sec
  end

  sig { returns(::Rational) }
  def sec_fraction
  end

  sig { returns(::Integer) }
  def second
  end

  sig { returns(::Rational) }
  def second_fraction
  end

  sig { returns(::String) }
  def strftime(format = '%FT%T%:z')
  end

  def to_date
  end

  sig { returns(::DateTime) }
  def to_datetime
  end

  sig { returns(::String) }
  def to_s
  end

  sig { returns(::Time) }
  def to_time
  end

  sig { returns(::String) }
  def xmlschema(n = nil)
  end

  sig { returns(::String) }
  def zone
  end
end

class Delegator < ::BasicObject
end

module Digest
  sig { returns(::String) }
  def self.hexencode(string)
  end

  private
  sig { returns(::String) }
  def hexencode(arg1)
  end

  class Base < ::Digest::Class
    def <<(arg1)
    end

    sig { returns(::Integer) }
    def block_length
    end

    sig { returns(::Integer) }
    def digest_length
    end

    def reset
    end

    def update(arg1)
    end

    private
    sig { returns(::String) }
    def finish
    end

    def initialize_copy(arg1)
    end
  end

  class Class
    include ::Digest::Instance

    sig { returns(::String) }
    def self.digest(string, *parameters)
    end

    sig { returns(::String) }
    def self.hexdigest(*args)
    end
  end

  module Instance
    def <<(arg1)
    end

    def ==(arg1)
    end

    sig { returns(::Integer) }
    def block_length
    end

    sig { returns(::String) }
    def digest(string = nil)
    end

    sig { returns(::String) }
    def digest!
    end

    sig { returns(::Integer) }
    def digest_length
    end

    sig { returns(::String) }
    def hexdigest(string = nil)
    end

    sig { returns(::String) }
    def hexdigest!
    end

    sig { returns(::String) }
    def inspect
    end

    sig { returns(::Integer) }
    def length
    end

    def new
    end

    def reset
    end

    sig { returns(::Integer) }
    def size
    end

    sig { returns(::String) }
    def to_s
    end

    def update(string)
    end

    private
    def finish
    end
  end

  class MD5 < ::Digest::Base
  end

  class RMD160 < ::Digest::Base
  end

  class SHA1 < ::Digest::Base
  end

  class SHA256 < ::Digest::Base
  end

  class SHA384 < ::Digest::Base
  end

  class SHA512 < ::Digest::Base
  end
end

class ERB
  module DefMethod
  end

  module Escape
    sig { returns(::String) }
    def self.html_escape(s)
    end

    private
    sig { returns(::String) }
    def html_escape(s)
    end
  end

  module Util
    include ::ERB::Escape

    sig { returns(::String) }
    def self.h(str)
    end

    sig { returns(::String) }
    def self.html_escape(s)
    end

    private
    sig { returns(::String) }
    def h(str)
    end
  end
end

module FileUtils
  include ::FileUtils::StreamUtils_
end

module Find
end

module Forwardable
end

class IPAddr
  include ::Comparable

  class AddressFamilyError < ::IPAddr::Error
  end

  class Error < ::ArgumentError
  end

  class InvalidAddressError < ::IPAddr::Error
  end

  class InvalidPrefixError < ::IPAddr::InvalidAddressError
  end
end

class IPSocket < ::BasicSocket
  sig { returns(::String) }
  def self.getaddress(host)
  end

  def addr(reverse_lookup = nil)
  end

  sig { returns(::String) }
  def inspect
  end

  def peeraddr(reverse_lookup = nil)
  end

  def recvfrom(maxlen, flags = nil)
  end
end

module JSON
  module Ext
    module Generator
      class State
      end
    end

    class Parser
    end
  end

  class GeneratorError < ::JSON::JSONError
  end

  class JSONError < ::StandardError
  end

  class NestingError < ::JSON::ParserError
  end

  class ParserError < ::JSON::JSONError
  end
end

module Kernel
  sig { returns(::Pathname) }
  def self.Pathname(path)
  end

  private
  sig { returns(::Pathname) }
  def Pathname(path)
  end
end

class Logger
  include ::Logger::Severity

  class Formatter
  end

  class LogDevice
    include ::Logger::Period
    include ::MonitorMixin
  end

  module Period
  end

  module Severity
  end
end

class Monitor
  def enter
  end

  def exit
  end

  def mon_check_owner
  end

  def mon_enter
  end

  def mon_exit
  end

  def mon_locked?
  end

  def mon_owned?
  end

  def mon_synchronize(&block)
  end

  def mon_try_enter
  end

  def synchronize(&block)
  end

  def try_enter
  end

  def try_mon_enter
  end

  def wait_for_cond(p1, p2)
  end
end

module MonitorMixin
  class ConditionVariable
  end
end

module Net
  class HTTP < ::Net::Protocol
    sig { returns(::Net::HTTP) }
    def self.newobj(address, port = nil, p_addr = nil, p_port = nil, p_user = nil, p_pass = nil, p_no_proxy = nil)
    end

    class Copy < ::Net::HTTPRequest
    end

    class Delete < ::Net::HTTPRequest
    end

    class Get < ::Net::HTTPRequest
    end

    class Head < ::Net::HTTPRequest
    end

    class Lock < ::Net::HTTPRequest
    end

    class Mkcol < ::Net::HTTPRequest
    end

    class Move < ::Net::HTTPRequest
    end

    class Options < ::Net::HTTPRequest
    end

    class Patch < ::Net::HTTPRequest
    end

    class Post < ::Net::HTTPRequest
    end

    class Propfind < ::Net::HTTPRequest
    end

    class Proppatch < ::Net::HTTPRequest
    end

    class Put < ::Net::HTTPRequest
    end

    class Trace < ::Net::HTTPRequest
    end

    class Unlock < ::Net::HTTPRequest
    end
  end

  class HTTPAccepted < ::Net::HTTPSuccess
  end

  class HTTPAlreadyReported < ::Net::HTTPSuccess
  end

  class HTTPBadGateway < ::Net::HTTPServerError
  end

  class HTTPBadRequest < ::Net::HTTPClientError
  end

  class HTTPBadResponse < ::StandardError
  end

  class HTTPClientError < ::Net::HTTPResponse
  end

  class HTTPConflict < ::Net::HTTPClientError
  end

  class HTTPContinue < ::Net::HTTPInformation
  end

  class HTTPCreated < ::Net::HTTPSuccess
  end

  class HTTPEarlyHints < ::Net::HTTPInformation
  end

  class HTTPError < ::Net::ProtocolError
    include ::Net::HTTPExceptions
  end

  module HTTPExceptions
    def data
    end
  end

  class HTTPExpectationFailed < ::Net::HTTPClientError
  end

  class HTTPFailedDependency < ::Net::HTTPClientError
  end

  class HTTPFatalError < ::Net::ProtoFatalError
    include ::Net::HTTPExceptions
  end

  class HTTPForbidden < ::Net::HTTPClientError
  end

  class HTTPFound < ::Net::HTTPRedirection
  end

  class HTTPGatewayTimeout < ::Net::HTTPServerError
  end

  class HTTPGenericRequest
    include ::Net::HTTPHeader
  end

  class HTTPGone < ::Net::HTTPClientError
  end

  module HTTPHeader
  end

  class HTTPHeaderSyntaxError < ::StandardError
  end

  class HTTPIMUsed < ::Net::HTTPSuccess
  end

  class HTTPInformation < ::Net::HTTPResponse
  end

  class HTTPInsufficientStorage < ::Net::HTTPServerError
  end

  class HTTPInternalServerError < ::Net::HTTPServerError
  end

  class HTTPLengthRequired < ::Net::HTTPClientError
  end

  class HTTPLocked < ::Net::HTTPClientError
  end

  class HTTPLoopDetected < ::Net::HTTPServerError
  end

  class HTTPMethodNotAllowed < ::Net::HTTPClientError
  end

  class HTTPMisdirectedRequest < ::Net::HTTPClientError
  end

  class HTTPMovedPermanently < ::Net::HTTPRedirection
  end

  class HTTPMultiStatus < ::Net::HTTPSuccess
  end

  class HTTPMultipleChoices < ::Net::HTTPRedirection
  end

  class HTTPNetworkAuthenticationRequired < ::Net::HTTPServerError
  end

  class HTTPNoContent < ::Net::HTTPSuccess
  end

  class HTTPNonAuthoritativeInformation < ::Net::HTTPSuccess
  end

  class HTTPNotAcceptable < ::Net::HTTPClientError
  end

  class HTTPNotExtended < ::Net::HTTPServerError
  end

  class HTTPNotFound < ::Net::HTTPClientError
  end

  class HTTPNotImplemented < ::Net::HTTPServerError
  end

  class HTTPNotModified < ::Net::HTTPRedirection
  end

  class HTTPOK < ::Net::HTTPSuccess
  end

  class HTTPPartialContent < ::Net::HTTPSuccess
  end

  class HTTPPayloadTooLarge < ::Net::HTTPClientError
  end

  class HTTPPaymentRequired < ::Net::HTTPClientError
  end

  class HTTPPermanentRedirect < ::Net::HTTPRedirection
  end

  class HTTPPreconditionFailed < ::Net::HTTPClientError
  end

  class HTTPPreconditionRequired < ::Net::HTTPClientError
  end

  class HTTPProcessing < ::Net::HTTPInformation
  end

  class HTTPProxyAuthenticationRequired < ::Net::HTTPClientError
  end

  class HTTPRangeNotSatisfiable < ::Net::HTTPClientError
  end

  class HTTPRedirection < ::Net::HTTPResponse
  end

  class HTTPRequest < ::Net::HTTPGenericRequest
  end

  class HTTPRequestHeaderFieldsTooLarge < ::Net::HTTPClientError
  end

  class HTTPRequestTimeout < ::Net::HTTPClientError
  end

  class HTTPResetContent < ::Net::HTTPSuccess
  end

  class HTTPResponse
    include ::Net::HTTPHeader
  end

  class HTTPRetriableError < ::Net::ProtoRetriableError
    include ::Net::HTTPExceptions
  end

  class HTTPSeeOther < ::Net::HTTPRedirection
  end

  class HTTPServerError < ::Net::HTTPResponse
  end

  class HTTPServiceUnavailable < ::Net::HTTPServerError
  end

  class HTTPSuccess < ::Net::HTTPResponse
  end

  class HTTPSwitchProtocol < ::Net::HTTPInformation
  end

  class HTTPTemporaryRedirect < ::Net::HTTPRedirection
  end

  class HTTPTooManyRequests < ::Net::HTTPClientError
  end

  class HTTPURITooLong < ::Net::HTTPClientError
  end

  class HTTPUnauthorized < ::Net::HTTPClientError
  end

  class HTTPUnavailableForLegalReasons < ::Net::HTTPClientError
  end

  class HTTPUnknownResponse < ::Net::HTTPResponse
  end

  class HTTPUnprocessableEntity < ::Net::HTTPClientError
  end

  class HTTPUnsupportedMediaType < ::Net::HTTPClientError
  end

  class HTTPUpgradeRequired < ::Net::HTTPClientError
  end

  class HTTPUseProxy < ::Net::HTTPRedirection
  end

  class HTTPVariantAlsoNegotiates < ::Net::HTTPServerError
  end

  class HTTPVersionNotSupported < ::Net::HTTPServerError
  end

  class OpenTimeout < ::Timeout::Error
  end

  class ProtoAuthError < ::Net::ProtocolError
  end

  class ProtoCommandError < ::Net::ProtocolError
  end

  class ProtoFatalError < ::Net::ProtocolError
  end

  class ProtoRetriableError < ::Net::ProtocolError
  end

  class ProtoServerError < ::Net::ProtocolError
  end

  class ProtoSyntaxError < ::Net::ProtocolError
  end

  class ProtoUnknownError < ::Net::ProtocolError
  end

  class Protocol
  end

  class ProtocolError < ::StandardError
  end

  class ReadTimeout < ::Timeout::Error
  end

  class WriteTimeout < ::Timeout::Error
  end
end

module ObjectSpace
  sig { returns(::String) }
  def self.allocation_class_path(object)
  end

  def self.allocation_generation(object)
  end

  sig { returns(::Symbol) }
  def self.allocation_method_id(object)
  end

  sig { returns(::String) }
  def self.allocation_sourcefile(object)
  end

  sig { returns(::Integer) }
  def self.allocation_sourceline(object)
  end

  sig { returns(::Hash) }
  def self.count_imemo_objects(result_hash = nil)
  end

  sig { returns(::Hash) }
  def self.count_nodes(result_hash = nil)
  end

  sig { returns(::Hash) }
  def self.count_objects_size(result_hash = nil)
  end

  sig { returns(::Hash) }
  def self.count_symbols(result_hash = nil)
  end

  sig { returns(::Hash) }
  def self.count_tdata_objects(result_hash = nil)
  end

  def self.internal_class_of(obj)
  end

  def self.internal_super_of(cls)
  end

  sig { returns(::Integer) }
  def self.memsize_of(obj)
  end

  sig { returns(::Integer) }
  def self.memsize_of_all(*args)
  end

  def self.reachable_objects_from(obj)
  end

  sig { returns(::Hash) }
  def self.reachable_objects_from_root
  end

  def self.trace_object_allocations(&block)
  end

  def self.trace_object_allocations_clear
  end

  def self.trace_object_allocations_debug_start
  end

  def self.trace_object_allocations_start
  end

  def self.trace_object_allocations_stop
  end

  private
  sig { returns(::String) }
  def allocation_class_path(object)
  end

  def allocation_generation(object)
  end

  sig { returns(::Symbol) }
  def allocation_method_id(object)
  end

  sig { returns(::String) }
  def allocation_sourcefile(object)
  end

  sig { returns(::Integer) }
  def allocation_sourceline(object)
  end

  sig { returns(::Hash) }
  def count_imemo_objects(result_hash = nil)
  end

  sig { returns(::Hash) }
  def count_nodes(result_hash = nil)
  end

  sig { returns(::Hash) }
  def count_objects_size(result_hash = nil)
  end

  sig { returns(::Hash) }
  def count_symbols(result_hash = nil)
  end

  sig { returns(::Hash) }
  def count_tdata_objects(result_hash = nil)
  end

  def internal_class_of(obj)
  end

  def internal_super_of(cls)
  end

  sig { returns(::Integer) }
  def memsize_of(obj)
  end

  sig { returns(::Integer) }
  def memsize_of_all(*args)
  end

  def reachable_objects_from(obj)
  end

  sig { returns(::Hash) }
  def reachable_objects_from_root
  end

  def trace_object_allocations_clear
  end

  def trace_object_allocations_debug_start
  end

  def trace_object_allocations_start
  end

  def trace_object_allocations_stop
  end
end

module Open3
end

module OpenSSL
  def self.debug
  end

  def self.debug=(arg1)
  end

  sig { returns(::Array) }
  def self.errors
  end

  def self.fips_mode
  end

  def self.fips_mode=(arg1)
  end

  def self.fixed_length_secure_compare(string, string2)
  end

  module ASN1
    sig { returns(::OpenSSL::ASN1::BMPString) }
    def self.BMPString(value, tag = nil, tagging = nil)
    end

    sig { returns(::OpenSSL::ASN1::BitString) }
    def self.BitString(value, tag = nil, tagging = nil)
    end

    sig { returns(::OpenSSL::ASN1::Boolean) }
    def self.Boolean(value, tag = nil, tagging = nil)
    end

    sig { returns(::OpenSSL::ASN1::EndOfContent) }
    def self.EndOfContent
    end

    sig { returns(::OpenSSL::ASN1::Enumerated) }
    def self.Enumerated(value, tag = nil, tagging = nil)
    end

    sig { returns(::OpenSSL::ASN1::GeneralString) }
    def self.GeneralString(value, tag = nil, tagging = nil)
    end

    sig { returns(::OpenSSL::ASN1::GeneralizedTime) }
    def self.GeneralizedTime(value, tag = nil, tagging = nil)
    end

    sig { returns(::OpenSSL::ASN1::GraphicString) }
    def self.GraphicString(value, tag = nil, tagging = nil)
    end

    sig { returns(::OpenSSL::ASN1::IA5String) }
    def self.IA5String(value, tag = nil, tagging = nil)
    end

    sig { returns(::OpenSSL::ASN1::ISO64String) }
    def self.ISO64String(value, tag = nil, tagging = nil)
    end

    sig { returns(::OpenSSL::ASN1::Integer) }
    def self.Integer(value, tag = nil, tagging = nil)
    end

    sig { returns(::OpenSSL::ASN1::Null) }
    def self.Null(*args)
    end

    sig { returns(::OpenSSL::ASN1::NumericString) }
    def self.NumericString(value, tag = nil, tagging = nil)
    end

    sig { returns(::OpenSSL::ASN1::ObjectId) }
    def self.ObjectId(value, tag = nil, tagging = nil)
    end

    sig { returns(::OpenSSL::ASN1::OctetString) }
    def self.OctetString(value, tag = nil, tagging = nil)
    end

    sig { returns(::OpenSSL::ASN1::PrintableString) }
    def self.PrintableString(value, tag = nil, tagging = nil)
    end

    sig { returns(::OpenSSL::ASN1::Sequence) }
    def self.Sequence(value, tag = nil, tagging = nil)
    end

    sig { returns(::OpenSSL::ASN1::Set) }
    def self.Set(value, tag = nil, tagging = nil)
    end

    sig { returns(::OpenSSL::ASN1::T61String) }
    def self.T61String(value, tag = nil, tagging = nil)
    end

    sig { returns(::OpenSSL::ASN1::UTCTime) }
    def self.UTCTime(value, tag = nil, tagging = nil)
    end

    sig { returns(::OpenSSL::ASN1::UTF8String) }
    def self.UTF8String(value, tag = nil, tagging = nil)
    end

    sig { returns(::OpenSSL::ASN1::UniversalString) }
    def self.UniversalString(value, tag = nil, tagging = nil)
    end

    sig { returns(::OpenSSL::ASN1::VideotexString) }
    def self.VideotexString(value, tag = nil, tagging = nil)
    end

    def self.decode(der)
    end

    sig { returns(::Array) }
    def self.decode_all(der)
    end

    def self.traverse(asn1, &block)
    end

    class ASN1Data
      sig { returns(::String) }
      def to_der
      end
    end

    class ASN1Error < ::OpenSSL::OpenSSLError
    end

    class BMPString < ::OpenSSL::ASN1::Primitive
    end

    class BitString < ::OpenSSL::ASN1::Primitive
    end

    class Boolean < ::OpenSSL::ASN1::Primitive
    end

    class Constructive < ::OpenSSL::ASN1::ASN1Data
      include ::OpenSSL::ASN1::TaggedASN1Data
      include ::Enumerable

      sig { returns(::String) }
      def to_der
      end
    end

    class EndOfContent < ::OpenSSL::ASN1::ASN1Data
      sig { returns(::String) }
      def to_der
      end
    end

    class Enumerated < ::OpenSSL::ASN1::Primitive
    end

    class GeneralString < ::OpenSSL::ASN1::Primitive
    end

    class GeneralizedTime < ::OpenSSL::ASN1::Primitive
    end

    class GraphicString < ::OpenSSL::ASN1::Primitive
    end

    class IA5String < ::OpenSSL::ASN1::Primitive
    end

    class ISO64String < ::OpenSSL::ASN1::Primitive
    end

    class Integer < ::OpenSSL::ASN1::Primitive
    end

    class Null < ::OpenSSL::ASN1::Primitive
    end

    class NumericString < ::OpenSSL::ASN1::Primitive
    end

    class ObjectId < ::OpenSSL::ASN1::Primitive
      def self.register(object_id, short_name, long_name)
      end

      def ==(arg1)
      end

      def ln
      end

      def long_name
      end

      sig { returns(::String) }
      def oid
      end

      def short_name
      end

      def sn
      end
    end

    class OctetString < ::OpenSSL::ASN1::Primitive
    end

    class Primitive < ::OpenSSL::ASN1::ASN1Data
      include ::OpenSSL::ASN1::TaggedASN1Data

      sig { returns(::String) }
      def to_der
      end
    end

    class PrintableString < ::OpenSSL::ASN1::Primitive
    end

    class Sequence < ::OpenSSL::ASN1::Constructive
    end

    class Set < ::OpenSSL::ASN1::Constructive
    end

    class T61String < ::OpenSSL::ASN1::Primitive
    end

    class UTCTime < ::OpenSSL::ASN1::Primitive
    end

    class UTF8String < ::OpenSSL::ASN1::Primitive
    end

    class UniversalString < ::OpenSSL::ASN1::Primitive
    end

    class VideotexString < ::OpenSSL::ASN1::Primitive
    end
  end

  class BN
    include ::Comparable

    def self.generate_prime(bits, safe = nil, add = nil, rem = nil)
    end

    def self.pseudo_rand(*args)
    end

    def self.pseudo_rand_range(arg1)
    end

    def self.rand(*args)
    end

    def self.rand_range(range)
    end

    def %(arg1)
    end

    def *(arg1)
    end

    def **(arg1)
    end

    def +(arg1)
    end

    def +@
    end

    def -(arg1)
    end

    def -@
    end

    def /(arg1)
    end

    def <<(arg1)
    end

    sig { returns(::Integer) }
    def <=>(arg1)
    end

    def ==(arg1)
    end

    def ===(arg1)
    end

    def >>(arg1)
    end

    def bit_set?(bit)
    end

    def clear_bit!(bit)
    end

    sig { returns(::Integer) }
    def cmp(bn2)
    end

    sig { returns(::Array) }
    def coerce(p1)
    end

    def copy(p1)
    end

    def eql?(obj)
    end

    def gcd(bn2)
    end

    sig { returns(::Integer) }
    def hash
    end

    def lshift!(bits)
    end

    def mask_bits!(arg1)
    end

    def mod_add(bn1, bn2)
    end

    def mod_exp(bn1, bn2)
    end

    def mod_inverse(bn2)
    end

    def mod_mul(bn1, bn2)
    end

    def mod_sqr(bn2)
    end

    def mod_sub(bn1, bn2)
    end

    def negative?
    end

    sig { returns(::Integer) }
    def num_bits
    end

    sig { returns(::Integer) }
    def num_bytes
    end

    def odd?
    end

    def one?
    end

    def prime?(checks = nil)
    end

    def prime_fasttest?(checks = nil, trial_div = nil)
    end

    def rshift!(bits)
    end

    def set_bit!(bit)
    end

    def sqr
    end

    def to_bn
    end

    sig { returns(::Integer) }
    def to_i
    end

    sig { returns(::Integer) }
    def to_int
    end

    sig { returns(::String) }
    def to_s(base = 10)
    end

    sig { returns(::Integer) }
    def ucmp(bn2)
    end

    def zero?
    end

    private
    def initialize_copy(p1)
    end
  end

  class BNError < ::OpenSSL::OpenSSLError
  end

  module Buffering
    include ::Enumerable

    class Buffer < ::String
    end
  end

  class Cipher
    sig { returns(::Array) }
    def self.ciphers
    end

    sig { returns(::String) }
    def auth_data=(arg1)
    end

    sig { returns(::String) }
    def auth_tag(tag_len = 16)
    end

    sig { returns(::String) }
    def auth_tag=(arg1)
    end

    sig { returns(::Integer) }
    def auth_tag_len=(arg1)
    end

    def authenticated?
    end

    sig { returns(::Integer) }
    def block_size
    end

    def decrypt
    end

    def encrypt
    end

    sig { returns(::String) }
    def final
    end

    sig { returns(::String) }
    def iv=(iv)
    end

    sig { returns(::Integer) }
    def iv_len
    end

    sig { returns(::Integer) }
    def iv_len=(arg1)
    end

    sig { returns(::String) }
    def key=(key)
    end

    sig { returns(::Integer) }
    def key_len
    end

    sig { returns(::Integer) }
    def key_len=(arg1)
    end

    sig { returns(::String) }
    def name
    end

    sig { returns(::Integer) }
    def padding=(arg1)
    end

    def pkcs5_keyivgen(pass, salt = nil, iterations = 2048, digest = "MD5")
    end

    def reset
    end

    sig { returns(::String) }
    def update(data, buffer = nil)
    end

    private
    sig { returns(::Array) }
    def ciphers
    end

    def initialize_copy(p1)
    end

    class AES < ::OpenSSL::Cipher
    end

    class AES128 < ::OpenSSL::Cipher
    end

    class AES192 < ::OpenSSL::Cipher
    end

    class AES256 < ::OpenSSL::Cipher
    end

    class BF < ::OpenSSL::Cipher
    end

    class CAST5 < ::OpenSSL::Cipher
    end

    class Cipher < ::OpenSSL::Cipher
    end

    class CipherError < ::OpenSSL::OpenSSLError
    end

    class DES < ::OpenSSL::Cipher
    end

    class IDEA < ::OpenSSL::Cipher
    end

    class RC2 < ::OpenSSL::Cipher
    end

    class RC4 < ::OpenSSL::Cipher
    end

    class RC5 < ::OpenSSL::Cipher
    end
  end

  class Config
    include ::Enumerable

    def self.load(filename = nil)
    end

    def self.parse(string)
    end

    sig { returns(::Hash) }
    def self.parse_config(io)
    end

    sig { returns(::Hash) }
    def [](arg1)
    end

    def each(&block)
    end

    def get_value(section, key)
    end

    sig { returns(::String) }
    def inspect
    end

    sig { returns(::Array) }
    def sections
    end

    sig { returns(::String) }
    def to_s
    end

    private
    def initialize_copy(p1)
    end
  end

  class ConfigError < ::OpenSSL::OpenSSLError
  end

  class Digest < ::Digest::Class
    def <<(arg1)
    end

    sig { returns(::Integer) }
    def block_length
    end

    sig { returns(::Integer) }
    def digest_length
    end

    sig { returns(::String) }
    def name
    end

    def reset
    end

    def update(string)
    end

    private
    def finish(*args)
    end

    def initialize_copy(p1)
    end

    class Digest < ::OpenSSL::Digest
    end

    class DigestError < ::OpenSSL::OpenSSLError
    end

    class MD4 < ::OpenSSL::Digest
      sig { returns(::String) }
      def self.digest(data)
      end

      sig { returns(::String) }
      def self.hexdigest(data)
      end
    end

    class MD5 < ::OpenSSL::Digest
      sig { returns(::String) }
      def self.digest(data)
      end

      sig { returns(::String) }
      def self.hexdigest(data)
      end
    end

    class RIPEMD160 < ::OpenSSL::Digest
      sig { returns(::String) }
      def self.digest(data)
      end

      sig { returns(::String) }
      def self.hexdigest(data)
      end
    end

    class SHA1 < ::OpenSSL::Digest
      sig { returns(::String) }
      def self.digest(data)
      end

      sig { returns(::String) }
      def self.hexdigest(data)
      end
    end

    class SHA224 < ::OpenSSL::Digest
      sig { returns(::String) }
      def self.digest(data)
      end

      sig { returns(::String) }
      def self.hexdigest(data)
      end
    end

    class SHA256 < ::OpenSSL::Digest
      sig { returns(::String) }
      def self.digest(data)
      end

      sig { returns(::String) }
      def self.hexdigest(data)
      end
    end

    class SHA384 < ::OpenSSL::Digest
      sig { returns(::String) }
      def self.digest(data)
      end

      sig { returns(::String) }
      def self.hexdigest(data)
      end
    end

    class SHA512 < ::OpenSSL::Digest
      sig { returns(::String) }
      def self.digest(data)
      end

      sig { returns(::String) }
      def self.hexdigest(data)
      end
    end
  end

  class HMAC
    def <<(arg1)
    end

    sig { returns(::String) }
    def digest
    end

    sig { returns(::String) }
    def hexdigest
    end

    sig { returns(::String) }
    def inspect
    end

    def reset
    end

    sig { returns(::String) }
    def to_s
    end

    def update(string)
    end

    private
    def initialize_copy(p1)
    end
  end

  class HMACError < ::OpenSSL::OpenSSLError
  end

  module KDF
    sig { returns(::String) }
    def self.hkdf(ikm)
    end

    sig { returns(::String) }
    def self.pbkdf2_hmac(pass)
    end

    sig { returns(::String) }
    def self.scrypt(pass, salt:, r:, p:, length:, **options)
    end

    private
    def hkdf(*args)
    end

    def pbkdf2_hmac(*args)
    end

    def scrypt(*args)
    end

    class KDFError < ::OpenSSL::OpenSSLError
    end
  end

  module Marshal
    module ClassMethods
    end
  end

  module Netscape
    class SPKI
      sig { returns(::String) }
      def challenge
      end

      sig { returns(::String) }
      def challenge=(arg1)
      end

      def public_key
      end

      def public_key=(arg1)
      end

      def sign(key, digest)
      end

      sig { returns(::String) }
      def to_der
      end

      sig { returns(::String) }
      def to_pem
      end

      sig { returns(::String) }
      def to_s
      end

      sig { returns(::String) }
      def to_text
      end

      def verify(key)
      end
    end

    class SPKIError < ::OpenSSL::OpenSSLError
    end
  end

  module OCSP
    class BasicResponse
      def add_nonce(nonce = nil)
      end

      def add_status(certificate_id, status, reason, revocation_time, this_update = nil, next_update = nil, extensions = nil)
      end

      sig { returns(::Integer) }
      def copy_nonce(request)
      end

      def find_response(certificate_id)
      end

      sig { returns(::Array) }
      def responses
      end

      def sign(cert, key, certs = nil, flags = 0, digest = nil)
      end

      sig { returns(::Integer) }
      def status
      end

      sig { returns(::String) }
      def to_der
      end

      def verify(certificates, store, flags = 0)
      end

      private
      def initialize_copy(p1)
      end
    end

    class CertificateId
      def cmp(other)
      end

      def cmp_issuer(other)
      end

      sig { returns(::String) }
      def hash_algorithm
      end

      sig { returns(::String) }
      def issuer_key_hash
      end

      sig { returns(::String) }
      def issuer_name_hash
      end

      sig { returns(::Integer) }
      def serial
      end

      sig { returns(::String) }
      def to_der
      end

      private
      def initialize_copy(p1)
      end
    end

    class OCSPError < ::OpenSSL::OpenSSLError
    end

    class Request
      def add_certid(certificate_id)
      end

      def add_nonce(nonce = nil)
      end

      sig { returns(::Array) }
      def certid
      end

      def check_nonce(response)
      end

      def sign(cert, key, certs = nil, flags = 0, digest = nil)
      end

      def signed?
      end

      sig { returns(::String) }
      def to_der
      end

      def verify(certificates, store, flags = 0)
      end

      private
      def initialize_copy(p1)
      end
    end

    class Response
      def self.create(status, basic_response = nil)
      end

      def basic
      end

      sig { returns(::Integer) }
      def status
      end

      sig { returns(::String) }
      def status_string
      end

      sig { returns(::String) }
      def to_der
      end

      private
      def initialize_copy(p1)
      end
    end

    class SingleResponse
      def cert_status
      end

      sig { returns(::OpenSSL::OCSP::CertificateId) }
      def certid
      end

      def check_validity(nsec = 0, maxsec = -1)
      end

      sig { returns(::Array) }
      def extensions
      end

      def next_update
      end

      def revocation_reason
      end

      def revocation_time
      end

      sig { returns(::Time) }
      def this_update
      end

      sig { returns(::String) }
      def to_der
      end

      private
      def initialize_copy(p1)
      end
    end
  end

  class OpenSSLError < ::StandardError
  end

  class PKCS12
    def self.create(pass, name, key, cert, ca = nil, key_pbe = nil, cert_pbe = nil, key_iter = nil, mac_iter = nil, keytype = nil)
    end

    def ca_certs
    end

    sig { returns(::OpenSSL::X509::Certificate) }
    def certificate
    end

    def key
    end

    sig { returns(::String) }
    def to_der
    end

    private
    def initialize_copy(p1)
    end

    class PKCS12Error < ::OpenSSL::OpenSSLError
    end
  end

  module PKCS5
  end

  class PKCS7
    def self.encrypt(certs, data, cipher = nil, flags = 0)
    end

    def self.read_smime(string)
    end

    def self.sign(certs, key, data, cipher = nil, flags = nil)
    end

    sig { returns(::String) }
    def self.write_smime(pkcs7, data = nil, flags = nil)
    end

    def add_certificate(p1)
    end

    def add_crl(p1)
    end

    def add_data(p1)
    end

    def add_recipient(p1)
    end

    def add_signer(p1)
    end

    def certificates
    end

    def certificates=(p1)
    end

    def cipher=(p1)
    end

    def crls
    end

    def crls=(p1)
    end

    def data
    end

    def data=(data)
    end

    sig { returns(::String) }
    def decrypt(p1, p2 = nil, p3 = nil)
    end

    def detached
    end

    def detached=(p1)
    end

    def detached?
    end

    def error_string
    end

    sig { returns(::String) }
    def error_string=(arg1)
    end

    sig { returns(::Array) }
    def recipients
    end

    sig { returns(::Array) }
    def signers
    end

    sig { returns(::String) }
    def to_der
    end

    sig { returns(::String) }
    def to_pem
    end

    sig { returns(::String) }
    def to_s
    end

    def type
    end

    sig { returns(::String) }
    def type=(arg1)
    end

    def verify(p1, p2, p3 = nil, p4 = nil)
    end

    private
    def initialize_copy(p1)
    end

    class PKCS7Error < ::OpenSSL::OpenSSLError
    end

    class RecipientInfo
      def enc_key
      end

      sig { returns(::OpenSSL::X509::Name) }
      def issuer
      end

      sig { returns(::Integer) }
      def serial
      end
    end

    class SignerInfo
      sig { returns(::OpenSSL::X509::Name) }
      def issuer
      end

      sig { returns(::Integer) }
      def serial
      end

      def signed_time
      end
    end
  end

  module PKey
    def self.read(pem, password = nil)
    end

    private
    def read(pem, password = nil)
    end

    class DH < ::OpenSSL::PKey::PKey
      include ::OpenSSL::Marshal

      sig { returns(::String) }
      def export
      end

      def g
      end

      sig { returns(::OpenSSL::BN) }
      def p
      end

      sig { returns(::Hash) }
      def params
      end

      def params_ok?
      end

      sig { returns(::OpenSSL::BN) }
      def priv_key
      end

      def private?
      end

      sig { returns(::OpenSSL::BN) }
      def pub_key
      end

      def public?
      end

      sig { returns(::OpenSSL::BN) }
      def q
      end

      def set_key(pub_key, priv_key)
      end

      def set_pqg(p, q, g)
      end

      sig { returns(::String) }
      def to_der
      end

      sig { returns(::String) }
      def to_pem
      end

      sig { returns(::String) }
      def to_s
      end
    end

    class DHError < ::OpenSSL::PKey::PKeyError
    end

    class DSA < ::OpenSSL::PKey::PKey
      include ::OpenSSL::Marshal

      sig { returns(::String) }
      def export(cipher = nil, password = nil)
      end

      sig { returns(::OpenSSL::BN) }
      def g
      end

      sig { returns(::OpenSSL::BN) }
      def p
      end

      sig { returns(::Hash) }
      def params
      end

      sig { returns(::OpenSSL::BN) }
      def priv_key
      end

      def private?
      end

      sig { returns(::OpenSSL::BN) }
      def pub_key
      end

      def public?
      end

      sig { returns(::OpenSSL::BN) }
      def q
      end

      def set_key(pub_key, priv_key)
      end

      def set_pqg(p, q, g)
      end

      sig { returns(::String) }
      def to_der
      end

      sig { returns(::String) }
      def to_pem(cipher = nil, password = nil)
      end

      sig { returns(::String) }
      def to_s(cipher = nil, password = nil)
      end
    end

    class DSAError < ::OpenSSL::PKey::PKeyError
    end

    class EC < ::OpenSSL::PKey::PKey
      include ::OpenSSL::Marshal

      sig { returns(::Array) }
      def self.builtin_curves
      end

      def self.generate(ec_group)
      end

      def check_key
      end

      sig { returns(::String) }
      def export(cipher = nil, password = nil)
      end

      def generate_key
      end

      def generate_key!
      end

      def group
      end

      sig { returns(::OpenSSL::PKey::EC::Group) }
      def group=(arg1)
      end

      def private?
      end

      def private_key
      end

      def private_key=(priv_key)
      end

      def private_key?
      end

      def public?
      end

      def public_key
      end

      def public_key=(priv_key)
      end

      def public_key?
      end

      sig { returns(::String) }
      def to_der
      end

      sig { returns(::String) }
      def to_pem(cipher = nil, password = nil)
      end

      class Group
        def ==(arg1)
        end

        sig { returns(::Integer) }
        def asn1_flag
        end

        sig { returns(::Integer) }
        def asn1_flag=(arg1)
        end

        sig { returns(::OpenSSL::BN) }
        def cofactor
        end

        sig { returns(::String) }
        def curve_name
        end

        sig { returns(::Integer) }
        def degree
        end

        def eql?(group2)
        end

        def generator
        end

        sig { returns(::OpenSSL::BN) }
        def order
        end

        def point_conversion_form
        end

        def point_conversion_form=(format)
        end

        def seed
        end

        sig { returns(::String) }
        def seed=(seed)
        end

        def set_generator(generator, order, cofactor)
        end

        sig { returns(::String) }
        def to_der
        end

        sig { returns(::String) }
        def to_pem
        end

        sig { returns(::String) }
        def to_text
        end

        private
        def initialize_copy(p1)
        end

        class Error < ::OpenSSL::OpenSSLError
        end
      end

      class Point
        def ==(arg1)
        end

        def add(point)
        end

        def eql?(point2)
        end

        sig { returns(::OpenSSL::PKey::EC::Group) }
        def group
        end

        def infinity?
        end

        def invert!
        end

        def make_affine!
        end

        def mul(*args)
        end

        def on_curve?
        end

        def set_to_infinity!
        end

        sig { returns(::String) }
        def to_octet_string(conversion_form)
        end

        private
        def initialize_copy(p1)
        end

        class Error < ::OpenSSL::OpenSSLError
        end
      end
    end

    class ECError < ::OpenSSL::PKey::PKeyError
    end

    class PKey
      sig { returns(::String) }
      def inspect
      end

      sig { returns(::String) }
      def oid
      end

      sig { returns(::String) }
      def private_to_der(cipher = nil, password = nil)
      end

      sig { returns(::String) }
      def private_to_pem(cipher = nil, password = nil)
      end

      sig { returns(::String) }
      def public_to_der
      end

      sig { returns(::String) }
      def public_to_pem
      end

      sig { returns(::String) }
      def sign(digest, data)
      end

      def verify(digest, signature, data)
      end
    end

    class PKeyError < ::OpenSSL::OpenSSLError
    end

    class RSA < ::OpenSSL::PKey::PKey
      include ::OpenSSL::Marshal

      def d
      end

      def dmp1
      end

      def dmq1
      end

      def e
      end

      sig { returns(::String) }
      def export(cipher = nil, password = nil)
      end

      def iqmp
      end

      def n
      end

      def p
      end

      sig { returns(::Hash) }
      def params
      end

      def private?
      end

      def public?
      end

      def q
      end

      def set_crt_params(dmp1, dmq1, iqmp)
      end

      def set_factors(p, q)
      end

      def set_key(n, e, d)
      end

      sig { returns(::String) }
      def sign_pss(digest, data)
      end

      sig { returns(::String) }
      def to_der
      end

      sig { returns(::String) }
      def to_pem(cipher = nil, password = nil)
      end

      sig { returns(::String) }
      def to_s(cipher = nil, password = nil)
      end

      def verify_pss(digest, signature, data)
      end
    end

    class RSAError < ::OpenSSL::PKey::PKeyError
    end
  end

  module Random
    def self.load_random_file(filename)
    end

    def self.random_add(str, entropy)
    end

    sig { returns(::String) }
    def self.random_bytes(length)
    end

    sig { returns(::String) }
    def self.seed(str)
    end

    def self.status?
    end

    def self.write_random_file(filename)
    end

    class RandomError < ::OpenSSL::OpenSSLError
    end
  end

  module SSL
    class SSLContext
      def add_certificate(certificate, pkey, extra_certs = nil)
      end

      def alpn_protocols
      end

      sig { returns(::Array) }
      def alpn_protocols=(arg1)
      end

      def alpn_select_cb
      end

      def alpn_select_cb=(alpn_select_callback)
      end

      sig { returns(::String) }
      def ca_file
      end

      sig { returns(::String) }
      def ca_file=(ca_file)
      end

      def ca_path
      end

      sig { returns(::String) }
      def ca_path=(ca_path)
      end

      def cert
      end

      sig { returns(::OpenSSL::X509::Certificate) }
      def cert=(cert)
      end

      def cert_store
      end

      sig { returns(::OpenSSL::X509::Store) }
      def cert_store=(store)
      end

      sig { returns(::Array) }
      def ciphers
      end

      def ciphers=(ciphers)
      end

      def client_ca
      end

      def client_ca=(client_ca)
      end

      def client_cert_cb
      end

      def client_cert_cb=(client_cert_cb)
      end

      sig { returns(::String) }
      def ecdh_curves=(ecdh_curves)
      end

      def enable_fallback_scsv
      end

      def extra_chain_cert
      end

      sig { returns(::Array) }
      def extra_chain_cert=(extra_certs)
      end

      def flush_sessions(time)
      end

      def freeze
      end

      def key
      end

      def key=(arg1)
      end

      def npn_protocols
      end

      def npn_protocols=(arg1)
      end

      def npn_select_cb
      end

      def npn_select_cb=(arg1)
      end

      sig { returns(::Integer) }
      def options
      end

      sig { returns(::Integer) }
      def options=(ssl_options)
      end

      def renegotiation_cb
      end

      def renegotiation_cb=(arg1)
      end

      sig { returns(::Integer) }
      def security_level
      end

      sig { returns(::Integer) }
      def security_level=(sec_level)
      end

      def session_add(session)
      end

      sig { returns(::Integer) }
      def session_cache_mode
      end

      sig { returns(::Integer) }
      def session_cache_mode=(integer)
      end

      sig { returns(::Integer) }
      def session_cache_size
      end

      sig { returns(::Integer) }
      def session_cache_size=(integer)
      end

      sig { returns(::Hash) }
      def session_cache_stats
      end

      def session_get_cb
      end

      def session_get_cb=(arg1)
      end

      def session_id_context
      end

      sig { returns(::Integer) }
      def session_id_context=(arg1)
      end

      def session_new_cb
      end

      def session_new_cb=(arg1)
      end

      def session_remove(session)
      end

      def session_remove_cb
      end

      def session_remove_cb=(arg1)
      end

      def setup
      end

      def ssl_timeout
      end

      sig { returns(::Integer) }
      def ssl_timeout=(arg1)
      end

      def timeout
      end

      sig { returns(::Integer) }
      def timeout=(arg1)
      end

      def verify_callback
      end

      def verify_callback=(arg1)
      end

      def verify_depth
      end

      sig { returns(::Integer) }
      def verify_depth=(arg1)
      end

      def verify_hostname
      end

      def verify_hostname=(arg1)
      end

      def verify_mode
      end

      def verify_mode=(arg1)
      end

      private
      def set_minmax_proto_version(min, max)
      end
    end

    class SSLError < ::OpenSSL::OpenSSLError
    end

    class SSLErrorWaitReadable < ::OpenSSL::SSL::SSLError
      include ::IO::WaitReadable
    end

    class SSLErrorWaitWritable < ::OpenSSL::SSL::SSLError
      include ::IO::WaitWritable
    end

    class SSLServer
      include ::OpenSSL::SSL::SocketForwarder
    end

    class SSLSocket
      include ::Enumerable
      include ::OpenSSL::Buffering
      include ::OpenSSL::SSL::SocketForwarder

      def accept
      end

      def accept_nonblock(exception: nil)
      end

      def alpn_protocol
      end

      def cert
      end

      def cipher
      end

      def client_ca
      end

      def connect
      end

      def connect_nonblock(exception: nil)
      end

      def finished_message
      end

      sig { returns(::String) }
      def hostname=(arg1)
      end

      def npn_protocol
      end

      def peer_cert
      end

      def peer_cert_chain
      end

      def peer_finished_message
      end

      sig { returns(::Integer) }
      def pending
      end

      sig { returns(::OpenSSL::SSL::Session) }
      def session=(arg1)
      end

      def session_reused?
      end

      def ssl_version
      end

      sig { returns(::String) }
      def state
      end

      sig { returns(::String) }
      def sysread(length, buffer = nil)
      end

      sig { returns(::Integer) }
      def syswrite(string)
      end

      def tmp_key
      end

      sig { returns(::Integer) }
      def verify_result
      end

      private
      def stop
      end

      def sysread_nonblock(length = nil, buffer = nil, *args)
      end

      def syswrite_nonblock(string = nil, *args)
      end
    end

    class Session
      def ==(arg1)
      end

      sig { returns(::String) }
      def id
      end

      sig { returns(::Time) }
      def time
      end

      sig { returns(::Time) }
      def time=(start_time)
      end

      sig { returns(::Integer) }
      def timeout
      end

      sig { returns(::Integer) }
      def timeout=(timeout)
      end

      sig { returns(::String) }
      def to_der
      end

      sig { returns(::String) }
      def to_pem
      end

      sig { returns(::String) }
      def to_text
      end

      private
      def initialize_copy(p1)
      end

      class SessionError < ::OpenSSL::OpenSSLError
      end
    end

    module SocketForwarder
    end
  end

  module Timestamp
    class Factory
      def additional_certs
      end

      def additional_certs=(certs)
      end

      def allowed_digests
      end

      sig { returns(::Array) }
      def allowed_digests=(arg1)
      end

      sig { returns(::OpenSSL::Timestamp::Response) }
      def create_timestamp(key, certificate, request)
      end

      def default_policy_id
      end

      sig { returns(::String) }
      def default_policy_id=(arg1)
      end

      def gen_time
      end

      sig { returns(::Time) }
      def gen_time=(arg1)
      end

      def serial_number
      end

      sig { returns(::Integer) }
      def serial_number=(arg1)
      end
    end

    class Request
      sig { returns(::String) }
      def algorithm
      end

      sig { returns(::String) }
      def algorithm=(arg1)
      end

      def cert_requested=(arg1)
      end

      def cert_requested?
      end

      def message_imprint
      end

      sig { returns(::String) }
      def message_imprint=(arg1)
      end

      def nonce
      end

      sig { returns(::OpenSSL::BN) }
      def nonce=(nonce)
      end

      def policy_id
      end

      sig { returns(::String) }
      def policy_id=(policy_id)
      end

      sig { returns(::String) }
      def to_der
      end

      sig { returns(::Integer) }
      def version
      end

      sig { returns(::Integer) }
      def version=(arg1)
      end
    end

    class Response
      def failure_info
      end

      sig { returns(::OpenSSL::BN) }
      def status
      end

      def status_text
      end

      sig { returns(::String) }
      def to_der
      end

      def token
      end

      def token_info
      end

      def tsa_certificate
      end

      def verify(request, store, intermediate_cert = nil)
      end
    end

    class TimestampError < ::OpenSSL::OpenSSLError
    end

    class TokenInfo
      def algorithm
      end

      sig { returns(::Time) }
      def gen_time
      end

      sig { returns(::String) }
      def message_imprint
      end

      def nonce
      end

      def ordering
      end

      def policy_id
      end

      def serial_number
      end

      sig { returns(::String) }
      def to_der
      end

      sig { returns(::Integer) }
      def version
      end
    end
  end

  module X509
    class Attribute
      include ::OpenSSL::Marshal

      sig { returns(::String) }
      def oid
      end

      sig { returns(::String) }
      def oid=(arg1)
      end

      sig { returns(::String) }
      def to_der
      end

      sig { returns(::OpenSSL::ASN1::Set) }
      def value
      end

      sig { returns(::OpenSSL::ASN1::Set) }
      def value=(arg1)
      end

      private
      def initialize_copy(p1)
      end
    end

    class AttributeError < ::OpenSSL::OpenSSLError
    end

    class CRL
      include ::OpenSSL::Marshal
      include ::OpenSSL::X509::Extension::Helpers
      include ::OpenSSL::X509::Extension::AuthorityKeyIdentifier

      sig { returns(::OpenSSL::X509::Extension) }
      def add_extension(p1)
      end

      sig { returns(::OpenSSL::X509::Revoked) }
      def add_revoked(p1)
      end

      sig { returns(::Array) }
      def extensions
      end

      sig { returns(::Array) }
      def extensions=(p1)
      end

      sig { returns(::OpenSSL::X509::Name) }
      def issuer
      end

      sig { returns(::OpenSSL::X509::Name) }
      def issuer=(p1)
      end

      def last_update
      end

      sig { returns(::Time) }
      def last_update=(p1)
      end

      def next_update
      end

      sig { returns(::Time) }
      def next_update=(p1)
      end

      sig { returns(::Array) }
      def revoked
      end

      sig { returns(::Array) }
      def revoked=(p1)
      end

      sig { returns(::String) }
      def sign(p1, p2)
      end

      sig { returns(::String) }
      def signature_algorithm
      end

      sig { returns(::String) }
      def to_der
      end

      sig { returns(::String) }
      def to_pem
      end

      sig { returns(::String) }
      def to_s
      end

      sig { returns(::String) }
      def to_text
      end

      def verify(p1)
      end

      sig { returns(::Integer) }
      def version
      end

      sig { returns(::Integer) }
      def version=(p1)
      end

      private
      def initialize_copy(p1)
      end
    end

    class CRLError < ::OpenSSL::OpenSSLError
    end

    class Certificate
      include ::OpenSSL::Marshal
      include ::OpenSSL::X509::Extension::Helpers
      include ::OpenSSL::X509::Extension::SubjectKeyIdentifier
      include ::OpenSSL::X509::Extension::AuthorityKeyIdentifier
      include ::OpenSSL::X509::Extension::CRLDistributionPoints
      include ::OpenSSL::X509::Extension::AuthorityInfoAccess

      def ==(arg1)
      end

      sig { returns(::OpenSSL::X509::Extension) }
      def add_extension(extension)
      end

      def check_private_key(key)
      end

      sig { returns(::Array) }
      def extensions
      end

      sig { returns(::Array) }
      def extensions=(arg1)
      end

      sig { returns(::String) }
      def inspect
      end

      sig { returns(::OpenSSL::X509::Name) }
      def issuer
      end

      sig { returns(::OpenSSL::X509::Name) }
      def issuer=(arg1)
      end

      def not_after
      end

      sig { returns(::Time) }
      def not_after=(arg1)
      end

      def not_before
      end

      sig { returns(::Time) }
      def not_before=(arg1)
      end

      def public_key
      end

      def public_key=(pkey)
      end

      sig { returns(::OpenSSL::BN) }
      def serial
      end

      def serial=(serial)
      end

      sig { returns(::String) }
      def sign(key, digest)
      end

      sig { returns(::String) }
      def signature_algorithm
      end

      sig { returns(::OpenSSL::X509::Name) }
      def subject
      end

      sig { returns(::OpenSSL::X509::Name) }
      def subject=(arg1)
      end

      sig { returns(::String) }
      def to_der
      end

      sig { returns(::String) }
      def to_pem
      end

      sig { returns(::String) }
      def to_s
      end

      sig { returns(::String) }
      def to_text
      end

      def verify(key)
      end

      sig { returns(::Integer) }
      def version
      end

      sig { returns(::Integer) }
      def version=(arg1)
      end

      private
      def initialize_copy(p1)
      end
    end

    class CertificateError < ::OpenSSL::OpenSSLError
    end

    class Extension
      include ::OpenSSL::Marshal

      def critical=(p1)
      end

      def critical?
      end

      sig { returns(::String) }
      def oid
      end

      sig { returns(::String) }
      def oid=(p1)
      end

      sig { returns(::String) }
      def to_der
      end

      sig { returns(::String) }
      def value
      end

      sig { returns(::String) }
      def value=(p1)
      end

      sig { returns(::String) }
      def value_der
      end

      private
      def initialize_copy(p1)
      end

      module AuthorityInfoAccess
        include ::OpenSSL::X509::Extension::Helpers
      end

      module AuthorityKeyIdentifier
        include ::OpenSSL::X509::Extension::Helpers
      end

      module CRLDistributionPoints
        include ::OpenSSL::X509::Extension::Helpers
      end

      module Helpers
      end

      module SubjectKeyIdentifier
        include ::OpenSSL::X509::Extension::Helpers
      end
    end

    class ExtensionError < ::OpenSSL::OpenSSLError
    end

    class ExtensionFactory
      def config
      end

      sig { returns(::OpenSSL::Config) }
      def config=(config)
      end

      sig { returns(::OpenSSL::X509::Extension) }
      def create_ext(oid, value, critical = nil)
      end

      def crl
      end

      sig { returns(::OpenSSL::X509::CRL) }
      def crl=(p1)
      end

      def issuer_certificate
      end

      sig { returns(::OpenSSL::X509::Certificate) }
      def issuer_certificate=(p1)
      end

      def subject_certificate
      end

      sig { returns(::OpenSSL::X509::Certificate) }
      def subject_certificate=(p1)
      end

      def subject_request
      end

      sig { returns(::OpenSSL::X509::Request) }
      def subject_request=(p1)
      end
    end

    class Name
      include ::Comparable
      include ::OpenSSL::Marshal

      def <=>(arg1)
      end

      def add_entry(oid, value, loc: nil, set: nil)
      end

      def cmp(other)
      end

      def eql?(other)
      end

      sig { returns(::Integer) }
      def hash
      end

      sig { returns(::Integer) }
      def hash_old
      end

      sig { returns(::String) }
      def inspect
      end

      sig { returns(::Array) }
      def to_a
      end

      sig { returns(::String) }
      def to_der
      end

      sig { returns(::String) }
      def to_s(format = nil)
      end

      sig { returns(::String) }
      def to_utf8
      end

      private
      def initialize_copy(p1)
      end

      module RFC2253DN
      end
    end

    class NameError < ::OpenSSL::OpenSSLError
    end

    class Request
      include ::OpenSSL::Marshal

      sig { returns(::OpenSSL::X509::Attribute) }
      def add_attribute(p1)
      end

      sig { returns(::Array) }
      def attributes
      end

      sig { returns(::Array) }
      def attributes=(p1)
      end

      def public_key
      end

      def public_key=(p1)
      end

      sig { returns(::String) }
      def sign(p1, p2)
      end

      sig { returns(::String) }
      def signature_algorithm
      end

      sig { returns(::OpenSSL::X509::Name) }
      def subject
      end

      sig { returns(::OpenSSL::X509::Name) }
      def subject=(p1)
      end

      sig { returns(::String) }
      def to_der
      end

      sig { returns(::String) }
      def to_pem
      end

      sig { returns(::String) }
      def to_s
      end

      sig { returns(::String) }
      def to_text
      end

      def verify(p1)
      end

      sig { returns(::Integer) }
      def version
      end

      sig { returns(::Integer) }
      def version=(p1)
      end

      private
      def initialize_copy(p1)
      end
    end

    class RequestError < ::OpenSSL::OpenSSLError
    end

    class Revoked
      sig { returns(::OpenSSL::X509::Extension) }
      def add_extension(p1)
      end

      sig { returns(::Array) }
      def extensions
      end

      sig { returns(::Array) }
      def extensions=(p1)
      end

      sig { returns(::Integer) }
      def serial
      end

      sig { returns(::Integer) }
      def serial=(p1)
      end

      def time
      end

      sig { returns(::Time) }
      def time=(p1)
      end

      sig { returns(::String) }
      def to_der
      end

      private
      def initialize_copy(p1)
      end
    end

    class RevokedError < ::OpenSSL::OpenSSLError
    end

    class Store
      def add_cert(cert)
      end

      def add_crl(crl)
      end

      def add_file(file)
      end

      def add_path(path)
      end

      def chain
      end

      def error
      end

      def error_string
      end

      sig { returns(::Integer) }
      def flags=(flags)
      end

      sig { returns(::Integer) }
      def purpose=(purpose)
      end

      def set_default_paths
      end

      sig { returns(::Time) }
      def time=(time)
      end

      sig { returns(::Integer) }
      def trust=(trust)
      end

      def verify(cert, chain = nil, &block)
      end

      def verify_callback
      end

      def verify_callback=(p1)
      end
    end

    class StoreContext
      def chain
      end

      sig { returns(::OpenSSL::X509::Certificate) }
      def current_cert
      end

      sig { returns(::OpenSSL::X509::CRL) }
      def current_crl
      end

      def error
      end

      sig { returns(::Integer) }
      def error=(error)
      end

      sig { returns(::Integer) }
      def error_depth
      end

      def error_string
      end

      sig { returns(::Integer) }
      def flags=(flags)
      end

      sig { returns(::Integer) }
      def purpose=(purpose)
      end

      sig { returns(::Time) }
      def time=(time)
      end

      sig { returns(::Integer) }
      def trust=(trust)
      end

      def verify
      end
    end

    class StoreError < ::OpenSSL::OpenSSLError
    end
  end
end

module OpenURI
  module Meta
  end

  module OpenRead
  end
end

class OptionParser
  module Acceptables
  end

  class AmbiguousArgument < ::OptionParser::InvalidArgument
  end

  class AmbiguousOption < ::OptionParser::ParseError
  end

  module Arguable
  end

  class CompletingHash < ::Hash
    include ::OptionParser::Completion
  end

  module Completion
  end

  class InvalidArgument < ::OptionParser::ParseError
  end

  class InvalidOption < ::OptionParser::ParseError
  end

  class List
  end

  class MissingArgument < ::OptionParser::ParseError
  end

  class NeedlessArgument < ::OptionParser::ParseError
  end

  class OptionMap < ::Hash
    include ::OptionParser::Completion
  end

  class ParseError < ::RuntimeError
  end

  class Switch
    class NoArgument < ::OptionParser::Switch
    end

    class OptionalArgument < ::OptionParser::Switch
    end

    class PlacedArgument < ::OptionParser::Switch
    end

    class RequiredArgument < ::OptionParser::Switch
    end
  end
end

class PP < ::PrettyPrint
  include ::PP::PPMethods

  module ObjectMixin
  end

  module PPMethods
  end

  class SingleLine < ::PrettyPrint::SingleLine
    include ::PP::PPMethods
  end
end

class PStore
end

class Pathname
  sig { returns(::Pathname) }
  def self.getwd
  end

  sig { params(block: NilClass).returns(::Array) }
  def self.glob(p1, p2 = nil, p3 = nil, &block)
  end

  sig { returns(::Pathname) }
  def self.pwd
  end

  def <=>(arg1)
  end

  def ==(arg1)
  end

  def ===(arg1)
  end

  sig { returns(::Time) }
  def atime
  end

  sig { returns(::Pathname) }
  def basename(p1 = nil)
  end

  sig { returns(::String) }
  def binread(length = nil, offset = nil)
  end

  sig { returns(::Integer) }
  def binwrite(*args)
  end

  sig { returns(::Time) }
  def birthtime
  end

  def blockdev?
  end

  def chardev?
  end

  sig { returns(::Integer) }
  def chmod(mode_int)
  end

  sig { returns(::Integer) }
  def chown(owner_int, group_int)
  end

  sig { returns(::Time) }
  def ctime
  end

  sig { returns(::Integer) }
  def delete
  end

  def directory?
  end

  sig { returns(::Pathname) }
  def dirname
  end

  def each_entry(&block)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def each_line(sep = nil, limit = nil, &block)
  end

  def empty?
  end

  sig { returns(::Array) }
  def entries
  end

  def eql?(arg1)
  end

  def executable?
  end

  def executable_real?
  end

  def exist?
  end

  sig { returns(::Pathname) }
  def expand_path(p1 = nil)
  end

  sig { returns(::String) }
  def extname
  end

  def file?
  end

  def fnmatch(pattern, flags = nil)
  end

  def fnmatch?(pattern, flags = nil)
  end

  sig { returns(::Pathname) }
  def freeze
  end

  sig { returns(::String) }
  def ftype
  end

  sig { params(block: NilClass).returns(::Array) }
  def glob(p1, p2 = nil, &block)
  end

  def grpowned?
  end

  sig { returns(::Integer) }
  def hash
  end

  sig { returns(::String) }
  def inspect
  end

  sig { returns(::Integer) }
  def lchmod(mode_int)
  end

  sig { returns(::Integer) }
  def lchown(owner_int, group_int)
  end

  sig { returns(::File::Stat) }
  def lstat
  end

  sig { returns(::Integer) }
  def lutime(p1, p2)
  end

  sig { returns(::Integer) }
  def make_link(old)
  end

  sig { returns(::Integer) }
  def make_symlink(old)
  end

  sig { returns(::Integer) }
  def mkdir(p1 = nil)
  end

  sig { returns(::Time) }
  def mtime
  end

  sig { params(block: NilClass).returns(::File) }
  def open(mode = nil, perm = nil, &block)
  end

  sig { params(block: NilClass).returns(::Dir) }
  def opendir(&block)
  end

  def owned?
  end

  def pipe?
  end

  sig { returns(::String) }
  def read(length = nil, offset = nil, mode: nil, flags: nil, external_encoding: nil, internal_encoding: nil, encoding: nil, textmode: nil, binmode: nil, autoclose: nil)
  end

  def readable?
  end

  def readable_real?
  end

  sig { returns(::Array) }
  def readlines(sep = nil, limit = nil)
  end

  def readlink
  end

  sig { returns(::Pathname) }
  def realdirpath(p1 = nil)
  end

  sig { returns(::Pathname) }
  def realpath(p1 = nil)
  end

  def rename(p1)
  end

  def rmdir
  end

  def setgid?
  end

  def setuid?
  end

  sig { returns(::Integer) }
  def size
  end

  def size?
  end

  def socket?
  end

  def split
  end

  sig { returns(::File::Stat) }
  def stat
  end

  def sticky?
  end

  sig { returns(::Pathname) }
  def sub(*args, &block)
  end

  sig { returns(::Pathname) }
  def sub_ext(p1)
  end

  def symlink?
  end

  sig { returns(::Integer) }
  def sysopen(mode = nil, perm = nil)
  end

  sig { returns(::String) }
  def to_path
  end

  sig { returns(::String) }
  def to_s
  end

  def truncate(p1)
  end

  sig { returns(::Integer) }
  def unlink
  end

  sig { returns(::Integer) }
  def utime(p1, p2)
  end

  def world_readable?
  end

  def world_writable?
  end

  def writable?
  end

  def writable_real?
  end

  sig { returns(::Integer) }
  def write(content, offset = nil, mode: nil, flags: nil, external_encoding: nil, internal_encoding: nil, encoding: nil, textmode: nil, binmode: nil, autoclose: nil)
  end

  def zero?
  end
end

class PrettyPrint
  class Breakable
  end

  class Group
  end

  class GroupQueue
  end

  class SingleLine
  end

  class Text
  end
end

module Psych
end

class Resolv
  class DNS
    class Config
      class NXDomain < ::Resolv::ResolvError
      end

      class OtherResolvError < ::Resolv::ResolvError
      end
    end

    class DecodeError < ::StandardError
    end

    class EncodeError < ::StandardError
    end

    module Label
      class Str
      end
    end

    class Message
      class MessageDecoder
      end

      class MessageEncoder
      end
    end

    class Name
    end

    module OpCode
    end

    class Query
    end

    module RCode
    end

    class Requester
      class ConnectedUDP < ::Resolv::DNS::Requester
        class Sender < ::Resolv::DNS::Requester::Sender
        end
      end

      class MDNSOneShot < ::Resolv::DNS::Requester::UnconnectedUDP
      end

      class RequestError < ::StandardError
      end

      class Sender
      end

      class TCP < ::Resolv::DNS::Requester
        class Sender < ::Resolv::DNS::Requester::Sender
        end
      end

      class UnconnectedUDP < ::Resolv::DNS::Requester
        class Sender < ::Resolv::DNS::Requester::Sender
        end
      end
    end

    class Resource < ::Resolv::DNS::Query
      class ANY < ::Resolv::DNS::Query
      end

      class CNAME < ::Resolv::DNS::Resource::DomainName
      end

      class DomainName < ::Resolv::DNS::Resource
      end

      class Generic < ::Resolv::DNS::Resource
      end

      class HINFO < ::Resolv::DNS::Resource
      end

      module IN
        class A < ::Resolv::DNS::Resource
        end

        class AAAA < ::Resolv::DNS::Resource
        end

        class SRV < ::Resolv::DNS::Resource
        end

        class WKS < ::Resolv::DNS::Resource
        end
      end

      class LOC < ::Resolv::DNS::Resource
      end

      class MINFO < ::Resolv::DNS::Resource
      end

      class MX < ::Resolv::DNS::Resource
      end

      class NS < ::Resolv::DNS::Resource::DomainName
      end

      class PTR < ::Resolv::DNS::Resource::DomainName
      end

      class SOA < ::Resolv::DNS::Resource
      end

      class TXT < ::Resolv::DNS::Resource
      end
    end
  end

  class Hosts
  end

  class IPv4
  end

  class IPv6
  end

  module LOC
    class Alt
    end

    class Coord
    end

    class Size
    end
  end

  class MDNS < ::Resolv::DNS
  end

  class ResolvError < ::StandardError
  end

  class ResolvTimeout < ::Timeout::Error
  end
end

class Ripper
  sig { returns(::Integer) }
  def self.dedent_string(input, width)
  end

  sig { returns(::String) }
  def self.lex_state_name(integer)
  end

  def column
  end

  def debug_output
  end

  def debug_output=(arg1)
  end

  sig { returns(::Encoding) }
  def encoding
  end

  def end_seen?
  end

  def error?
  end

  sig { returns(::String) }
  def filename
  end

  def lineno
  end

  def parse
  end

  def state
  end

  def token
  end

  def yydebug
  end

  def yydebug=(arg1)
  end

  private
  sig { returns(::Integer) }
  def dedent_string(input, width)
  end

  class Filter
  end

  class Lexer < ::Ripper
    class Elem
    end

    class State
    end
  end

  class SexpBuilder < ::Ripper
  end

  class SexpBuilderPP < ::Ripper::SexpBuilder
  end

  class TokenPattern
    sig { returns(::Ripper::TokenPattern) }
    def self.compile(pattern)
    end

    class CompileError < ::Ripper::TokenPattern::Error
    end

    class Error < ::StandardError
    end

    class MatchData
    end

    class MatchError < ::Ripper::TokenPattern::Error
    end
  end
end

module SecureRandom
end

module Shellwords
end

class SimpleDelegator < ::Delegator
end

module SingleForwardable
end

module Singleton
  include ::Singleton::SingletonInstanceMethods

  module SingletonClassMethods
  end
end

class Socket < ::BasicSocket
  def self.getaddrinfo(*args)
  end

  def self.gethostbyaddr(ip)
  end

  def self.gethostbyname(hostname)
  end

  sig { returns(::String) }
  def self.gethostname
  end

  sig { returns(::Array) }
  def self.getifaddrs
  end

  sig { returns(::Array) }
  def self.getnameinfo(sockaddr)
  end

  sig { returns(::Integer) }
  def self.getservbyname(service_name, protocol_name = nil)
  end

  sig { returns(::String) }
  def self.getservbyport(service_port, layer4_proto = nil)
  end

  sig { returns(::Array) }
  def self.ip_address_list
  end

  sig { returns(::String) }
  def self.pack_sockaddr_in(port, host)
  end

  sig { returns(::String) }
  def self.pack_sockaddr_un(path)
  end

  def self.pair(domain, type, protocol)
  end

  sig { returns(::String) }
  def self.sockaddr_in(port, host)
  end

  sig { returns(::String) }
  def self.sockaddr_un(path)
  end

  def self.socketpair(domain, type, protocol)
  end

  def self.unpack_sockaddr_in(sockaddr)
  end

  sig { returns(::String) }
  def self.unpack_sockaddr_un(sockaddr)
  end

  def accept
  end

  def bind(local_sockaddr)
  end

  sig { returns(::Integer) }
  def connect(remote_sockaddr)
  end

  def listen(int)
  end

  def recvfrom(maxlen, flags = nil)
  end

  def sysaccept
  end

  private
  def __accept_nonblock(arg1)
  end

  def __connect_nonblock(arg1, arg2)
  end

  def __recvfrom_nonblock(arg1, arg2, arg3, arg4)
  end

  class AncillaryData
    def self.int(family, cmsg_level, cmsg_type, integer)
    end

    def self.ip_pktinfo(addr, ifindex, spec_dst = nil)
    end

    def self.ipv6_pktinfo(addr, ifindex)
    end

    def self.unix_rights(fd)
    end

    def cmsg_is?(level, type)
    end

    sig { returns(::String) }
    def data
    end

    sig { returns(::Integer) }
    def family
    end

    sig { returns(::String) }
    def inspect
    end

    sig { returns(::Integer) }
    def int
    end

    def ip_pktinfo
    end

    def ipv6_pktinfo
    end

    sig { returns(::Addrinfo) }
    def ipv6_pktinfo_addr
    end

    sig { returns(::Integer) }
    def ipv6_pktinfo_ifindex
    end

    sig { returns(::Integer) }
    def level
    end

    sig { returns(::Time) }
    def timestamp
    end

    sig { returns(::Integer) }
    def type
    end

    def unix_rights
    end
  end

  module Constants
  end

  class Ifaddr
    def addr
    end

    def broadaddr
    end

    def dstaddr
    end

    sig { returns(::Integer) }
    def flags
    end

    sig { returns(::Integer) }
    def ifindex
    end

    sig { returns(::String) }
    def inspect
    end

    sig { returns(::String) }
    def name
    end

    def netmask
    end
  end

  class UDPSource
  end
end

class SocketError < ::StandardError
end

class TCPServer < ::TCPSocket
  def accept
  end

  def listen(int)
  end

  sig { returns(::Integer) }
  def sysaccept
  end

  private
  def __accept_nonblock(arg1)
  end
end

class TCPSocket < ::IPSocket
  def self.gethostbyname(hostname)
  end
end

module TSort
  class Cyclic < ::StandardError
  end
end

class Tempfile
end

class Time
  include ::Comparable

  def to_date
  end

  sig { returns(::DateTime) }
  def to_datetime
  end

  sig { returns(::Time) }
  def to_time
  end
end

module Timeout
  class Error < ::RuntimeError
  end

  class ExitException < ::Exception
  end
end

class UDPSocket < ::IPSocket
  def bind(host, port)
  end

  def connect(host, port)
  end

  sig { returns(::Integer) }
  def send(mesg, flags = nil, host = nil, port = nil)
  end

  private
  def __recvfrom_nonblock(arg1, arg2, arg3, arg4)
  end
end

class UNIXServer < ::UNIXSocket
  def accept
  end

  def listen(int)
  end

  sig { returns(::Integer) }
  def sysaccept
  end

  private
  def __accept_nonblock(arg1)
  end
end

class UNIXSocket < ::BasicSocket
  def self.pair(socktype = nil, protocol = nil)
  end

  def self.socketpair(socktype = nil, protocol = nil)
  end

  def addr
  end

  sig { returns(::String) }
  def path
  end

  def peeraddr
  end

  def recv_io(*args)
  end

  def recvfrom(maxlen, flags = nil, outbuf = nil)
  end

  def send_io(io)
  end
end

module URI
  class BadURIError < ::URI::Error
  end

  class Error < ::StandardError
  end

  class FTP < ::URI::Generic
    include ::OpenURI::OpenRead
  end

  class File < ::URI::Generic
  end

  class Generic
    include ::URI
  end

  class HTTP < ::URI::Generic
    include ::OpenURI::OpenRead
  end

  class HTTPS < ::URI::HTTP
  end

  class InvalidComponentError < ::URI::Error
  end

  class InvalidURIError < ::URI::Error
  end

  class LDAP < ::URI::Generic
  end

  class LDAPS < ::URI::LDAP
  end

  class MailTo < ::URI::Generic
    include ::URI::RFC2396_REGEXP
  end

  class RFC2396_Parser
    include ::URI::RFC2396_REGEXP
  end

  module RFC2396_REGEXP
  end

  class RFC3986_Parser
  end

  class WS < ::URI::Generic
  end

  class WSS < ::URI::WS
  end
end
