# Return types for stdlib methods written in Ruby, which the stdlib's own
# source does not say. Generated by `script/stdlib_sigs.rb` from rbs 3.8.0 and Ruby 3.4.9's
# stdlib; do not edit by hand (DEC-220).
#
# Never a location: each `def` lends its `sig` to the real one in the
# stdlib, as core's stub does for `Set` (DEC-182).

class Addrinfo
  sig { params(block: NilClass).returns(::Socket) }
  def bind(&block)
  end

  sig { params(block: NilClass).returns(::Socket) }
  def connect(timeout: nil, &block)
  end

  sig { params(block: NilClass).returns(::Socket) }
  def connect_from(*args, timeout: nil, &block)
  end

  sig { params(block: NilClass).returns(::Socket) }
  def connect_to(*args, timeout: nil, &block)
  end

  sig { returns(::Addrinfo) }
  def family_addrinfo(*args)
  end
end

class Array
  include ::Enumerable
  include ::JSON::Ext::Generator::GeneratorMethods::Array

  sig { returns(::Array) }
  def self.[](*args)
  end

  sig { returns(::Array) }
  def self.new(*args, &block)
  end

  sig { returns(::Integer) }
  def count(object = nil, &block)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  sig { params(block: T.proc.void).returns(::Array) }
  def filter(&block)
  end

  sig { returns(::String) }
  def inspect
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def keep_if(&block)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  sig { params(block: T.proc.void).returns(::Array) }
  def map(&block)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def reject(&block)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  sig { params(block: T.proc.void).returns(::Array) }
  def select(&block)
  end

  sig { returns(::String) }
  def shelljoin
  end

  sig { returns(::String) }
  def to_s
  end

  sig { returns(::Array) }
  def union(*other_arrays)
  end
end

class BasicSocket < ::IO
  sig { returns(::Addrinfo) }
  def connect_address
  end

  sig { returns(::Integer) }
  def sendmsg(mesg, flags = nil, dest_sockaddr = nil, *controls)
  end
end

module Benchmark
  sig { params(block: T.proc.void).returns(::Array) }
  def self.benchmark(caption = nil, label_width = nil, format = nil, *labels, &block)
  end

  sig { params(blk: T.proc.void).returns(::Array) }
  def self.bm(label_width = nil, *labels, &blk)
  end

  sig { params(block: T.proc.void).returns(::Array) }
  def self.bmbm(width = nil, &block)
  end

  sig { params(block: T.proc.void).returns(::Benchmark::Tms) }
  def self.measure(label = nil, &block)
  end

  sig { params(block: T.proc.void).returns(::Float) }
  def self.realtime(&block)
  end

  private
  sig { params(block: T.proc.void).returns(::Array) }
  def benchmark(caption = nil, label_width = nil, format = nil, *labels, &block)
  end

  sig { params(blk: T.proc.void).returns(::Array) }
  def bm(label_width = nil, *labels, &blk)
  end

  sig { params(block: T.proc.void).returns(::Array) }
  def bmbm(width = nil, &block)
  end

  sig { params(block: T.proc.void).returns(::Benchmark::Tms) }
  def measure(label = nil, &block)
  end

  sig { params(block: T.proc.void).returns(::Float) }
  def realtime(&block)
  end

  class Job
    sig { returns(::Array) }
    def list
    end

    sig { returns(::Integer) }
    def width
    end
  end

  class Report
    sig { params(blk: T.proc.void).returns(::Benchmark::Tms) }
    def item(label = nil, *format, &blk)
    end

    sig { returns(::Array) }
    def list
    end

    sig { params(blk: T.proc.void).returns(::Benchmark::Tms) }
    def report(label = nil, *format, &blk)
    end
  end

  class Tms
    sig { returns(::Float) }
    def cstime
    end

    sig { returns(::Float) }
    def cutime
    end

    sig { returns(::String) }
    def format(format = nil, *args)
    end

    sig { returns(::String) }
    def label
    end

    sig { returns(::Float) }
    def real
    end

    sig { returns(::Float) }
    def stime
    end

    sig { returns(::String) }
    def to_s
    end

    sig { returns(::Float) }
    def total
    end

    sig { returns(::Float) }
    def utime
    end
  end
end

class CGI
  include ::CGI::Util
  include ::CGI::Escape

  sig { returns(::Hash) }
  def self.parse(query)
  end

  sig { returns(::String) }
  def header(options = nil)
  end

  sig { returns(::String) }
  def http_header(options = nil)
  end

  class Cookie < ::Array
    sig { returns(::Hash) }
    def self.parse(raw_cookie)
    end

    sig { returns(::String) }
    def domain=(str)
    end

    sig { returns(::Time) }
    def expires=(arg1)
    end

    sig { returns(::String) }
    def inspect
    end

    sig { returns(::String) }
    def name
    end

    sig { returns(::String) }
    def name=(str)
    end

    sig { returns(::String) }
    def path=(str)
    end

    sig { returns(::String) }
    def to_s
    end

    sig { returns(::Array) }
    def value
    end
  end

  module QueryExtension
    sig { returns(::Hash) }
    def cookies
    end

    sig { returns(::Hash) }
    def cookies=(arg1)
    end

    sig { returns(::Hash) }
    def files
    end

    sig { returns(::Array) }
    def keys(*args)
    end

    sig { returns(::Hash) }
    def params
    end

    sig { returns(::Hash) }
    def params=(hash)
    end

    private
    sig { returns(::String) }
    def read_from_cmdline
    end
  end

  module Util
    include ::CGI::Escape

    sig { returns(::String) }
    def escapeElement(string, *elements)
    end

    sig { returns(::String) }
    def escape_element(string, *elements)
    end

    sig { returns(::String) }
    def pretty(string, shift = nil)
    end

    sig { returns(::String) }
    def rfc1123_date(time)
    end

    sig { returns(::String) }
    def unescapeElement(string, *elements)
    end

    sig { returns(::String) }
    def unescape_element(string, *elements)
    end
  end
end

class Complex < ::Numeric
  sig { returns(::Complex) }
  def *(arg1)
  end

  sig { returns(::Complex) }
  def +(arg1)
  end

  sig { returns(::Complex) }
  def -(arg1)
  end

  sig { returns(::Complex) }
  def -@
  end

  sig { returns(::Complex) }
  def /(arg1)
  end

  sig { returns(::Integer) }
  def hash
  end

  sig { returns(::String) }
  def inspect
  end

  sig { returns(::Float) }
  def to_f
  end

  sig { returns(::Integer) }
  def to_i
  end

  sig { returns(::String) }
  def to_s
  end
end

module Coverage
  sig { returns(::Array) }
  def self.line_stub(file)
  end
end

class Data
  sig { returns(::Integer) }
  def hash
  end

  sig { returns(::String) }
  def inspect
  end

  sig { returns(::String) }
  def to_s
  end
end

class Delegator < ::BasicObject
  sig { returns(::Proc) }
  def self.delegating_block(mid)
  end

  sig { returns(::Array) }
  def methods(all = nil)
  end

  sig { returns(::Array) }
  def protected_methods(all = nil)
  end

  sig { returns(::Array) }
  def public_methods(all = nil)
  end
end

module Digest
  class Class
    include ::Digest::Instance

    sig { returns(::String) }
    def self.base64digest(str, *args)
    end
  end

  module Instance
    sig { returns(::String) }
    def base64digest(str = nil)
    end

    sig { returns(::String) }
    def base64digest!
    end
  end
end

class Dir
  include ::Enumerable

  sig { params(block: NilClass).returns(::Enumerator) }
  def self.foreach(dirname, encoding: nil, &block)
  end

  sig { params(block: NilClass).returns(::String) }
  def self.mktmpdir(prefix_suffix = nil, *rest, **options, &block)
  end

  sig { returns(::String) }
  def self.tmpdir
  end

  sig { returns(::Array) }
  def children
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def each(&block)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def each_child(&block)
  end

  sig { returns(::Integer) }
  def fileno
  end

  sig { returns(::String) }
  def inspect
  end
end

class ERB
  sig { returns(::String) }
  def self.version
  end

  sig { returns(::Encoding) }
  def encoding
  end

  sig { returns(::Integer) }
  def lineno
  end

  sig { returns(::String) }
  def result(b = nil)
  end

  sig { returns(::String) }
  def result_with_hash(hash)
  end

  sig { returns(::String) }
  def src
  end

  module Util
    include ::ERB::Escape

    sig { returns(::String) }
    def self.u(s)
    end

    sig { returns(::String) }
    def self.url_encode(s)
    end

    private
    sig { returns(::String) }
    def u(s)
    end

    sig { returns(::String) }
    def url_encode(s)
    end
  end
end

class Encoding
  sig { returns(::String) }
  def inspect
  end

  sig { returns(::String) }
  def to_s
  end

  class Converter
    sig { returns(::String) }
    def convert(source_string)
    end

    sig { returns(::String) }
    def finish
    end

    sig { returns(::String) }
    def inspect
    end
  end
end

module Enumerable
  sig { returns(::Array) }
  def compact
  end
end

class Enumerator
  include ::Enumerable

  sig { returns(::String) }
  def inspect
  end

  class Lazy < ::Enumerator
    sig { returns(::Enumerator::Lazy) }
    def compact
    end
  end

  class Product < ::Enumerator
    sig { returns(::String) }
    def inspect
    end
  end

  class Yielder
    sig { returns(::Proc) }
    def to_proc
    end
  end
end

class Exception
  sig { returns(::String) }
  def detailed_message(highlight: false, **kwargs)
  end

  sig { returns(::String) }
  def inspect
  end
end

class File < ::IO
  sig { returns(::Integer) }
  def self.chmod(mode, *args)
  end

  sig { returns(::Integer) }
  def self.chown(owner, group, *args)
  end

  sig { returns(::File::Stat) }
  def self.lstat(filepath)
  end

  sig { returns(::String) }
  def self.path(path)
  end

  sig { returns(::Integer) }
  def size
  end

  class Stat
    include ::Comparable

    sig { returns(::String) }
    def inspect
    end

    sig { returns(::Integer) }
    def size
    end
  end
end

module FileTest
  sig { returns(::Integer) }
  def self.size(file_name)
  end

  private
  sig { returns(::Integer) }
  def size(file_name)
  end
end

module FileUtils
  include ::FileUtils::StreamUtils_

  sig { returns(::Array) }
  def self.collect_method(opt)
  end

  sig { returns(::Array) }
  def self.commands
  end

  sig { returns(::String) }
  def self.getwd
  end

  sig { returns(::Array) }
  def self.options
  end

  sig { returns(::Array) }
  def self.options_of(mid)
  end

  sig { returns(::String) }
  def self.pwd
  end

  private
  sig { returns(::String) }
  def getwd
  end

  sig { returns(::String) }
  def pwd
  end
end

module Find
  sig { params(block: NilClass).returns(::Enumerator) }
  def self.find(*paths, ignore_error: nil, &block)
  end

  private
  sig { params(block: NilClass).returns(::Enumerator) }
  def find(*paths, ignore_error: nil, &block)
  end
end

class Float < ::Numeric
  include ::JSON::Ext::Generator::GeneratorMethods::Float

  sig { returns(::Integer) }
  def hash
  end

  sig { returns(::String) }
  def inspect
  end

  sig { returns(::Integer) }
  def to_i
  end

  sig { returns(::String) }
  def to_s
  end
end

module GC
  module Profiler
    sig { returns(::String) }
    def self.result
    end
  end
end

class Hash
  include ::Enumerable
  include ::JSON::Ext::Generator::GeneratorMethods::Hash

  sig { returns(::Hash) }
  def self.[](*args)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  sig { params(block: T.proc.void).returns(::Hash) }
  def filter(&block)
  end

  sig { returns(::Array) }
  def flatten(level = nil)
  end

  sig { returns(::Integer) }
  def hash
  end

  sig { returns(::String) }
  def inspect
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  sig { params(block: T.proc.void).returns(::Hash) }
  def reject(&block)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  sig { params(block: T.proc.void).returns(::Hash) }
  def select(&block)
  end

  sig { returns(::String) }
  def to_s
  end
end

class IO
  include ::Enumerable
  include ::File::Constants

  sig { returns(::Integer) }
  def self.copy_stream(src, dst, src_length = nil, src_offset = 0)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def self.foreach(path, sep = nil, limit = nil, **opts, &block)
  end

  sig { returns(::String) }
  def self.read(path, length = nil, offset = 0, **opts)
  end

  sig { returns(::Array) }
  def self.readlines(path, sep = nil, limit = nil, **opts)
  end

  sig { returns(::Integer) }
  def self.write(path, data, offset = 0, **opts)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def each(sep = nil, limit = nil, chomp: nil, &block)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def each_byte(&block)
  end

  sig { returns(::Integer) }
  def fcntl(integer_cmd, argument)
  end

  sig { returns(::String) }
  def inspect
  end

  sig { returns(::Integer) }
  def lineno
  end

  sig { returns(::Integer) }
  def readbyte
  end

  sig { returns(::String) }
  def readchar
  end

  sig { returns(::String) }
  def readpartial(maxlen, out_string = nil)
  end

  sig { returns(::File::Stat) }
  def stat
  end

  sig { returns(::Integer) }
  def to_i
  end

  class Buffer
    include ::Comparable

    sig { returns(::IO::Buffer) }
    def self.for(string, &block)
    end

    sig { returns(::IO::Buffer) }
    def self.map(file, size = nil, offset = nil, flags = nil)
    end

    sig { params(block: T.proc.void).returns(::String) }
    def self.string(length, &block)
    end

    sig { returns(::Integer) }
    def <=>(arg1)
    end

    sig { returns(::Integer) }
    def copy(source, offset = nil, length = nil, source_offset = nil)
    end

    sig { returns(::String) }
    def get_string(offset = nil, length = nil, encoding = nil)
    end

    sig { returns(::String) }
    def inspect
    end

    sig { returns(::Integer) }
    def size
    end

    sig { returns(::String) }
    def to_s
    end
  end
end

class IPAddr
  include ::Comparable

  sig { returns(::IPAddr) }
  def self.new_ntoh(addr)
  end

  sig { returns(::String) }
  def self.ntop(addr)
  end

  sig { returns(::IPAddr) }
  def &(other)
  end

  sig { returns(::IPAddr) }
  def <<(num)
  end

  sig { returns(::IPAddr) }
  def >>(num)
  end

  sig { returns(::Integer) }
  def family
  end

  sig { returns(::Integer) }
  def hash
  end

  sig { returns(::String) }
  def hton
  end

  sig { returns(::String) }
  def inspect
  end

  sig { returns(::String) }
  def ip6_arpa
  end

  sig { returns(::String) }
  def ip6_int
  end

  sig { returns(::IPAddr) }
  def ipv4_compat
  end

  sig { returns(::IPAddr) }
  def ipv4_mapped
  end

  sig { returns(::IPAddr) }
  def mask(prefixlen)
  end

  sig { returns(::IPAddr) }
  def native
  end

  sig { returns(::Integer) }
  def prefix
  end

  sig { returns(::String) }
  def reverse
  end

  sig { returns(::IPAddr) }
  def succ
  end

  sig { returns(::Integer) }
  def to_i
  end

  sig { returns(::Range) }
  def to_range
  end

  sig { returns(::String) }
  def to_s
  end

  sig { returns(::String) }
  def to_string
  end

  sig { returns(::IPAddr) }
  def |(other)
  end

  sig { returns(::IPAddr) }
  def ~
  end
end

class Integer < ::Numeric
  include ::JSON::Ext::Generator::GeneratorMethods::Integer

  sig { returns(::Integer) }
  def &(arg1)
  end

  sig { returns(::Integer) }
  def <<(arg1)
  end

  sig { returns(::Integer) }
  def >>(arg1)
  end

  sig { returns(::Integer) }
  def [](*args)
  end

  sig { returns(::Integer) }
  def ^(arg1)
  end

  sig { returns(::String) }
  def inspect(base = nil)
  end

  sig { returns(::Float) }
  def to_f
  end

  sig { returns(::Integer) }
  def |(arg1)
  end
end

module JSON
  sig { returns(::String) }
  def self.fast_generate(obj, opts = nil)
  end

  sig { returns(::String) }
  def self.fast_unparse(obj, opts = nil)
  end

  sig { returns(::String) }
  def self.generate(obj, opts = nil)
  end

  sig { returns(::String) }
  def self.iconv(to, from, string)
  end

  sig { returns(::String) }
  def self.unparse(obj, opts = nil)
  end

  private
  sig { returns(::String) }
  def fast_generate(obj, opts = nil)
  end

  sig { returns(::String) }
  def fast_unparse(obj, opts = nil)
  end

  sig { returns(::String) }
  def generate(obj, opts = nil)
  end

  sig { returns(::String) }
  def unparse(obj, opts = nil)
  end
end

module Kernel
  sig { returns(::String) }
  def self.format(format, *args)
  end

  sig { returns(::String) }
  def self.readline(sep = nil, limit = nil, chomp: false)
  end

  sig { returns(::Array) }
  def self.readlines(sep = nil, limit = nil, chomp: false, **enc_opts)
  end

  sig { returns(::Array) }
  def self.select(read_ios, write_ios = [], error_ios = [], timeout = nil)
  end

  sig { returns(::String) }
  def pretty_inspect
  end

  sig { returns(::Array) }
  def protected_methods(all = true)
  end

  private
  sig { returns(::String) }
  def readline(sep = nil, limit = nil, chomp: false)
  end

  sig { returns(::Array) }
  def readlines(sep = nil, limit = nil, chomp: false, **enc_opts)
  end

  sig { returns(::Array) }
  def select(read_ios, write_ios = [], error_ios = [], timeout = nil)
  end
end

class LocalJumpError < ::StandardError
  sig { returns(::Symbol) }
  def reason
  end
end

class Logger
  include ::Logger::Severity

  sig { returns(::Integer) }
  def debug!
  end

  sig { returns(::Integer) }
  def error!
  end

  sig { returns(::Integer) }
  def fatal!
  end

  sig { returns(::Integer) }
  def info!
  end

  sig { returns(::Integer) }
  def level
  end

  sig { returns(::Integer) }
  def level=(severity)
  end

  sig { returns(::Integer) }
  def sev_threshold
  end

  sig { returns(::Integer) }
  def sev_threshold=(severity)
  end

  sig { returns(::Integer) }
  def warn!
  end

  private
  sig { returns(::String) }
  def format_severity(severity)
  end

  class Formatter
    sig { returns(::String) }
    def call(severity, time, progname, msg)
    end

    private
    sig { returns(::String) }
    def msg2str(msg)
    end
  end

  class LogDevice
    include ::Logger::Period
    include ::MonitorMixin

    private
    sig { returns(::File) }
    def create_logfile(filename)
    end

    sig { returns(::File) }
    def open_logfile(filename)
    end
  end
end

class MatchData
  sig { returns(::Integer) }
  def hash
  end

  sig { returns(::String) }
  def inspect
  end

  sig { returns(::Integer) }
  def length
  end

  sig { returns(::Regexp) }
  def regexp
  end

  sig { returns(::Integer) }
  def size
  end

  sig { returns(::String) }
  def string
  end

  sig { returns(::String) }
  def to_s
  end

  sig { returns(::Array) }
  def values_at(*indexes)
  end
end

class Method
  sig { returns(::Proc) }
  def <<(arg1)
  end

  sig { returns(::Proc) }
  def >>(arg1)
  end

  sig { returns(::Integer) }
  def hash
  end

  sig { returns(::String) }
  def inspect
  end

  sig { returns(::Symbol) }
  def original_name
  end

  sig { returns(::String) }
  def to_s
  end
end

class Module
  sig { returns(::String) }
  def inspect
  end

  sig { returns(::String) }
  def to_s
  end
end

class Monitor
  sig { returns(::MonitorMixin::ConditionVariable) }
  def new_cond
  end
end

module MonitorMixin
  sig { returns(::MonitorMixin::ConditionVariable) }
  def new_cond
  end

  class ConditionVariable
    sig { returns(::Thread::ConditionVariable) }
    def broadcast
    end

    sig { returns(::Thread::ConditionVariable) }
    def signal
    end
  end
end

module Net
  class HTTP < ::Net::Protocol
    sig { returns(::Integer) }
    def self.default_port
    end

    sig { returns(::String) }
    def self.get(uri_or_host, path_or_headers = nil, port = nil)
    end

    sig { returns(::Integer) }
    def self.http_default_port
    end

    sig { returns(::Integer) }
    def self.https_default_port
    end

    sig { returns(::FalseClass) }
    def self.is_version_1_1?
    end

    sig { returns(::TrueClass) }
    def self.is_version_1_2?
    end

    sig { returns(::Net::HTTP) }
    def self.new(address, port = nil, p_addr = nil, p_port = nil, p_user = nil, p_pass = nil, p_no_proxy = nil, p_use_ssl = nil)
    end

    sig { params(block: NilClass).returns(::Net::HTTP) }
    def self.start(address, *arg, &block)
    end

    sig { returns(::FalseClass) }
    def self.version_1_1?
    end

    sig { returns(::TrueClass) }
    def self.version_1_2
    end

    sig { returns(::TrueClass) }
    def self.version_1_2?
    end

    sig { returns(::String) }
    def address
    end

    sig { returns(::String) }
    def inspect
    end

    sig { returns(::String) }
    def local_host
    end

    sig { returns(::String) }
    def local_host=(arg1)
    end

    sig { returns(::Integer) }
    def local_port
    end

    sig { returns(::Integer) }
    def local_port=(arg1)
    end

    sig { returns(::Integer) }
    def max_retries
    end

    sig { returns(::Integer) }
    def max_retries=(retries)
    end

    sig { returns(::Integer) }
    def port
    end

    sig { params(block: NilClass).returns(::Net::HTTP) }
    def start(&block)
    end
  end

  class HTTPGenericRequest
    include ::Net::HTTPHeader

    sig { returns(::String) }
    def inspect
    end

    sig { returns(::String) }
    def method
    end

    sig { returns(::String) }
    def path
    end
  end

  module HTTPHeader
    sig { params(block: NilClass).returns(::Enumerator) }
    sig { params(block: T.proc.void).returns(::Hash) }
    def canonical_each(&block)
    end

    sig { params(block: NilClass).returns(::Enumerator) }
    sig { params(block: T.proc.void).returns(::Hash) }
    def each(&block)
    end

    sig { params(block: NilClass).returns(::Enumerator) }
    sig { params(block: T.proc.void).returns(::Hash) }
    def each_capitalized(&block)
    end

    sig { params(block: NilClass).returns(::Enumerator) }
    sig { params(block: T.proc.void).returns(::Hash) }
    def each_capitalized_name(&block)
    end

    sig { params(block: NilClass).returns(::Enumerator) }
    sig { params(block: T.proc.void).returns(::Hash) }
    def each_header(&block)
    end

    sig { params(block: NilClass).returns(::Enumerator) }
    sig { params(block: T.proc.void).returns(::Hash) }
    def each_key(&block)
    end

    sig { params(block: NilClass).returns(::Enumerator) }
    sig { params(block: T.proc.void).returns(::Hash) }
    def each_name(&block)
    end

    sig { params(block: NilClass).returns(::Enumerator) }
    sig { params(block: T.proc.void).returns(::Hash) }
    def each_value(&block)
    end

    sig { params(key: T.untyped, block: NilClass).returns(::String) }
    def fetch(key, *args, &block)
    end

    sig { returns(::Integer) }
    def length
    end

    sig { returns(::Range) }
    def range=(r, e = nil)
    end

    sig { returns(::Range) }
    def set_range(r, e = nil)
    end

    sig { returns(::Integer) }
    def size
    end

    sig { returns(::Hash) }
    def to_hash
    end

    sig { returns(::Hash) }
    def type_params
    end

    private
    sig { returns(::String) }
    def basic_encode(account, password)
    end

    sig { returns(::String) }
    def capitalize(name)
    end
  end

  class HTTPResponse
    include ::Net::HTTPHeader

    sig { returns(::String) }
    def body
    end

    sig { returns(::String) }
    def code
    end

    sig { returns(::String) }
    def entity
    end

    sig { returns(::String) }
    def http_version
    end

    sig { returns(::String) }
    def inspect
    end

    sig { returns(::String) }
    def message
    end

    sig { returns(::String) }
    def msg
    end

    sig { returns(::String) }
    def read_body(dest = nil, &block)
    end
  end
end

class Numeric
  include ::Comparable

  sig { returns(::Integer) }
  def <=>(arg1)
  end
end

module ObjectSpace
  class WeakKeyMap
    sig { returns(::String) }
    def inspect
    end
  end
end

module OpenSSL
  module ASN1
    class BitString < ::OpenSSL::ASN1::Primitive
      sig { returns(::Integer) }
      def unused_bits
      end

      sig { returns(::Integer) }
      def unused_bits=(arg1)
      end
    end
  end

  module Buffering
    include ::Enumerable

    sig { returns(::String) }
    def readchar
    end

    sig { returns(::String) }
    def readline(eol = nil)
    end

    sig { returns(::Array) }
    def readlines(eol = nil)
    end

    sig { returns(::String) }
    def readpartial(maxlen, buf = nil)
    end

    sig { returns(::String) }
    def ungetc(c)
    end

    sig { returns(::Integer) }
    def write(*s)
    end
  end

  class Cipher
    sig { returns(::String) }
    def random_iv
    end

    sig { returns(::String) }
    def random_key
    end
  end

  class Digest < ::Digest::Class
    sig { returns(::String) }
    def self.digest(name, data)
    end
  end

  class HMAC
    sig { returns(::String) }
    def self.base64digest(digest, key, data)
    end

    sig { returns(::String) }
    def self.digest(digest, key, data)
    end

    sig { returns(::String) }
    def self.hexdigest(digest, key, data)
    end

    sig { returns(::String) }
    def base64digest
    end
  end

  module PKCS5
    sig { returns(::String) }
    def self.pbkdf2_hmac(pass, salt, iter, keylen, digest)
    end

    sig { returns(::String) }
    def self.pbkdf2_hmac_sha1(pass, salt, iter, keylen)
    end
  end

  module PKey
    class DH < ::OpenSSL::PKey::PKey
      include ::OpenSSL::Marshal

      sig { returns(::OpenSSL::PKey::DH) }
      def self.new(*args, &blk)
      end

      sig { returns(::String) }
      def compute_key(pub_bn)
      end
    end

    class DSA < ::OpenSSL::PKey::PKey
      include ::OpenSSL::Marshal

      sig { returns(::OpenSSL::PKey::DSA) }
      def self.new(*args, &blk)
      end

      sig { returns(::String) }
      def syssign(string)
      end
    end

    class EC < ::OpenSSL::PKey::PKey
      include ::OpenSSL::Marshal

      sig { returns(::String) }
      def dh_compute_key(pubkey)
      end

      sig { returns(::String) }
      def dsa_sign_asn1(data)
      end

      class Point
        sig { returns(::OpenSSL::BN) }
        def to_bn(conversion_form = nil)
        end
      end
    end

    class RSA < ::OpenSSL::PKey::PKey
      include ::OpenSSL::Marshal

      sig { returns(::OpenSSL::PKey::RSA) }
      def self.new(*args, &blk)
      end

      sig { returns(::String) }
      def private_decrypt(data, padding = nil)
      end

      sig { returns(::String) }
      def private_encrypt(string, padding = nil)
      end

      sig { returns(::String) }
      def public_decrypt(string, padding = nil)
      end

      sig { returns(::String) }
      def public_encrypt(data, padding = nil)
      end
    end
  end

  module SSL
    class SSLServer
      include ::OpenSSL::SSL::SocketForwarder

      sig { returns(::OpenSSL::SSL::SSLSocket) }
      def accept
      end
    end

    class SSLSocket
      include ::Enumerable
      include ::OpenSSL::Buffering
      include ::OpenSSL::SSL::SocketForwarder

      sig { returns(::OpenSSL::SSL::SSLContext) }
      def context
      end
    end

    module SocketForwarder
      sig { returns(::Integer) }
      def fileno
      end
    end
  end

  module X509
    class Extension
      include ::OpenSSL::Marshal

      sig { returns(::Hash) }
      def to_h
      end

      sig { returns(::String) }
      def to_s
      end
    end

    class ExtensionFactory
      sig { returns(::OpenSSL::X509::Extension) }
      def create_ext_from_array(ary)
      end

      sig { returns(::OpenSSL::X509::Extension) }
      def create_ext_from_hash(hash)
      end

      sig { returns(::OpenSSL::X509::Extension) }
      def create_ext_from_string(str)
      end

      sig { returns(::OpenSSL::X509::Extension) }
      def create_extension(*arg)
      end
    end

    class Name
      include ::Comparable
      include ::OpenSSL::Marshal

      module RFC2253DN
        private
        sig { returns(::Array) }
        def scan(dn)
        end
      end
    end
  end
end

module OpenURI
  module Meta
    sig { returns(::Array) }
    def content_encoding
    end

    sig { returns(::String) }
    def content_type
    end

    sig { returns(::Hash) }
    def meta
    end
  end

  module OpenRead
    sig { returns(::String) }
    def read(options = nil)
    end
  end
end

class OptionParser
  sig { returns(::Hash) }
  def self.getopts(*args, symbolize_names: nil)
  end

  sig { returns(::OptionParser::List) }
  def self.top
  end

  sig { returns(::String) }
  def banner
  end

  sig { returns(::String) }
  def banner=(arg1)
  end

  sig { returns(::OptionParser::List) }
  def base
  end

  sig { returns(::Array) }
  def candidate(word)
  end

  sig { returns(::Array) }
  def default_argv
  end

  sig { returns(::Array) }
  def default_argv=(arg1)
  end

  sig { returns(::Hash) }
  def getopts(*args, symbolize_names: nil, **keywords)
  end

  sig { returns(::String) }
  def help
  end

  sig { returns(::Array) }
  def order(*argv, **keywords, &nonopt)
  end

  sig { returns(::Array) }
  def order!(argv = nil, into: nil, **keywords, &nonopt)
  end

  sig { returns(::Array) }
  def parse(*argv, **keywords)
  end

  sig { returns(::Array) }
  def parse!(argv = nil, **keywords)
  end

  sig { returns(::Array) }
  def permute(*argv, **keywords)
  end

  sig { returns(::Array) }
  def permute!(argv = nil, **keywords)
  end

  sig { returns(::String) }
  def program_name
  end

  sig { returns(::String) }
  def program_name=(arg1)
  end

  sig { returns(::String) }
  def set_banner(arg1)
  end

  sig { returns(::String) }
  def set_program_name(arg1)
  end

  sig { returns(::String) }
  def set_summary_indent(arg1)
  end

  sig { returns(::Integer) }
  def set_summary_width(arg1)
  end

  sig { returns(::String) }
  def summary_indent
  end

  sig { returns(::String) }
  def summary_indent=(arg1)
  end

  sig { returns(::Integer) }
  def summary_width
  end

  sig { returns(::Integer) }
  def summary_width=(arg1)
  end

  sig { returns(::Array) }
  def to_a
  end

  sig { returns(::String) }
  def to_s
  end

  sig { returns(::OptionParser::List) }
  def top
  end

  module Arguable
    sig { returns(::Hash) }
    def getopts(*args, symbolize_names: nil, **keywords)
    end

    sig { params(block: NilClass).returns(::OptionParser) }
    def options(&block)
    end

    sig { returns(::Array) }
    def order!(**keywords, &blk)
    end

    sig { returns(::Array) }
    def parse!(**keywords)
    end

    sig { returns(::Array) }
    def permute!(**keywords)
    end
  end

  class ParseError < ::RuntimeError
    sig { returns(::String) }
    def message
    end

    sig { returns(::String) }
    def to_s
    end
  end
end

class PP < ::PrettyPrint
  include ::PP::PPMethods

  sig { returns(::Integer) }
  def self.width_for(out)
  end

  module ObjectMixin
    sig { returns(::Array) }
    def pretty_print_instance_variables
    end
  end

  module PPMethods
    sig { params(block: T.proc.void).returns(::Integer) }
    def object_address_group(obj, &block)
    end

    sig { params(block: T.proc.void).returns(::Integer) }
    def object_group(obj, &block)
    end
  end
end

class PStore
  sig { returns(::Array) }
  def roots
  end
end

class Pathname
  sig { returns(::Pathname) }
  def +(other)
  end

  sig { returns(::Pathname) }
  def /(other)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def ascend(&block)
  end

  sig { returns(::Array) }
  def children(with_directory = nil)
  end

  sig { returns(::Pathname) }
  def cleanpath(consider_symlink = nil)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def descend(&block)
  end

  sig { params(b: NilClass).returns(::Enumerator) }
  sig { params(b: T.proc.void).returns(::Array) }
  def each_child(with_directory = nil, &b)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def each_filename(&block)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def find(ignore_error: nil, &block)
  end

  sig { returns(::Pathname) }
  def join(*args)
  end

  sig { returns(::Pathname) }
  def parent
  end

  sig { returns(::Pathname) }
  def relative_path_from(base_directory)
  end
end

class PrettyPrint
  sig { returns(::PrettyPrint::Group) }
  def current_group
  end

  sig { returns(::Integer) }
  def flush
  end

  sig { returns(::Proc) }
  def genspace
  end

  sig { params(block: T.proc.void).returns(::Integer) }
  def group(indent = nil, open_obj = nil, close_obj = nil, open_width = nil, close_width = nil, &block)
  end

  sig { returns(::PrettyPrint::GroupQueue) }
  def group_queue
  end

  sig { returns(::Integer) }
  def indent
  end

  sig { returns(::Integer) }
  def maxwidth
  end

  sig { returns(::String) }
  def newline
  end

  class Breakable
    sig { returns(::Integer) }
    def indent
    end

    sig { returns(::String) }
    def obj
    end

    sig { returns(::Integer) }
    def width
    end
  end

  class Group
    sig { returns(::Array) }
    def breakables
    end
  end

  class Text
    sig { returns(::Integer) }
    def width
    end
  end
end

class Proc
  sig { returns(::Proc) }
  def <<(arg1)
  end

  sig { returns(::Proc) }
  def >>(arg1)
  end

  sig { returns(::Integer) }
  def hash
  end

  sig { returns(::String) }
  def inspect
  end

  sig { returns(::String) }
  def to_s
  end
end

module Process
  class Status
    sig { returns(::Integer) }
    def &(arg1)
    end

    sig { returns(::Integer) }
    def >>(arg1)
    end

    sig { returns(::String) }
    def inspect
    end

    sig { returns(::Integer) }
    def to_i
    end

    sig { returns(::String) }
    def to_s
    end
  end
end

class Random < ::Random::Base
  sig { returns(::String) }
  def self.bytes(size)
  end

  class Base
    include ::Random::Formatter

    sig { returns(::String) }
    def bytes(size)
    end
  end

  module Formatter
    sig { returns(::String) }
    def base64(n = nil)
    end

    sig { returns(::String) }
    def hex(n = nil)
    end

    sig { returns(::String) }
    def random_bytes(n = nil)
    end

    sig { returns(::String) }
    def urlsafe_base64(n = nil, padding = nil)
    end

    sig { returns(::String) }
    def uuid
    end
  end
end

class Range
  include ::Enumerable

  sig { returns(::Integer) }
  def hash
  end

  sig { returns(::String) }
  def inspect
  end

  sig { returns(::String) }
  def to_s
  end
end

class Rational < ::Numeric
  sig { returns(::Rational) }
  def -@
  end

  sig { returns(::Rational) }
  def abs
  end

  sig { returns(::Integer) }
  def hash
  end

  sig { returns(::String) }
  def inspect
  end

  sig { returns(::Float) }
  def to_f
  end

  sig { returns(::Integer) }
  def to_i
  end

  sig { returns(::String) }
  def to_s
  end
end

module RbConfig
  sig { returns(::String) }
  def self.expand(val, config = nil)
  end

  sig { returns(::String) }
  def self.ruby
  end
end

class Regexp
  sig { returns(::Regexp) }
  def self.compile(pattern, options = nil, timeout: nil)
  end

  sig { returns(::Integer) }
  def hash
  end

  sig { returns(::String) }
  def inspect
  end

  sig { returns(::String) }
  def to_s
  end
end

class Resolv
  sig { returns(::String) }
  def self.getaddress(name)
  end

  sig { returns(::Array) }
  def self.getaddresses(name)
  end

  sig { returns(::String) }
  def self.getname(address)
  end

  sig { returns(::Array) }
  def self.getnames(address)
  end

  sig { returns(::String) }
  def getaddress(name)
  end

  sig { returns(::Array) }
  def getaddresses(name)
  end

  sig { returns(::String) }
  def getname(address)
  end

  sig { returns(::Array) }
  def getnames(address)
  end

  class DNS
    sig { returns(::Integer) }
    def self.allocate_request_id(host, port)
    end

    sig { returns(::Array) }
    def getaddresses(name)
    end

    sig { returns(::Resolv::DNS::Name) }
    def getname(address)
    end

    sig { returns(::Array) }
    def getnames(address)
    end

    sig { returns(::Array) }
    def getresources(name, typeclass)
    end

    sig { returns(::Resolv::DNS::Requester::TCP) }
    def make_tcp_requester(host, port)
    end

    class Config
      sig { returns(::Hash) }
      def self.default_config_hash(filename = nil)
      end

      sig { returns(::Hash) }
      def self.parse_resolv_conf(filename)
      end

      sig { returns(::Array) }
      def generate_candidates(name)
      end

      sig { returns(::Array) }
      def generate_timeouts
      end

      sig { returns(::Array) }
      def nameserver_port
      end
    end

    module Label
      class Str
        sig { returns(::String) }
        def downcase
        end

        sig { returns(::Integer) }
        def hash
        end

        sig { returns(::String) }
        def inspect
        end

        sig { returns(::String) }
        def string
        end

        sig { returns(::String) }
        def to_s
        end
      end
    end

    class Message
      sig { returns(::Integer) }
      def aa
      end

      sig { returns(::Array) }
      def additional
      end

      sig { returns(::Array) }
      def answer
      end

      sig { returns(::Array) }
      def authority
      end

      sig { returns(::String) }
      def encode
      end

      sig { returns(::Integer) }
      def id
      end

      sig { returns(::Integer) }
      def opcode
      end

      sig { returns(::Integer) }
      def qr
      end

      sig { returns(::Array) }
      def question
      end

      sig { returns(::Integer) }
      def ra
      end

      sig { returns(::Integer) }
      def rcode
      end

      sig { returns(::Integer) }
      def rd
      end

      sig { returns(::Integer) }
      def tc
      end

      class MessageDecoder
        sig { returns(::String) }
        def get_bytes(len = nil)
        end

        sig { returns(::Resolv::DNS::Label::Str) }
        def get_label
        end

        sig { returns(::Array) }
        def get_labels
        end

        sig { params(block: T.proc.void).returns(::Integer) }
        def get_length16(&block)
        end

        sig { returns(::Resolv::DNS::Name) }
        def get_name
        end

        sig { returns(::String) }
        def get_string
        end

        sig { returns(::Array) }
        def get_string_list
        end

        sig { returns(::Array) }
        def get_unpack(template)
        end

        sig { returns(::String) }
        def inspect
        end
      end
    end

    class Name
      sig { returns(::Integer) }
      def hash
      end

      sig { returns(::String) }
      def inspect
      end

      sig { returns(::Integer) }
      def length
      end

      sig { returns(::Array) }
      def to_a
      end
    end

    class Requester
      class ConnectedUDP < ::Resolv::DNS::Requester
        class Sender < ::Resolv::DNS::Requester::Sender
          sig { returns(::String) }
          def data
          end
        end
      end

      class TCP < ::Resolv::DNS::Requester
        class Sender < ::Resolv::DNS::Requester::Sender
          sig { returns(::String) }
          def data
          end
        end
      end

      class UnconnectedUDP < ::Resolv::DNS::Requester
        class Sender < ::Resolv::DNS::Requester::Sender
          sig { returns(::String) }
          def data
          end
        end
      end
    end

    class Resource < ::Resolv::DNS::Query
      sig { returns(::Integer) }
      def hash
      end

      sig { returns(::Integer) }
      def ttl
      end

      class DomainName < ::Resolv::DNS::Resource
        sig { returns(::String) }
        def name
        end
      end

      class Generic < ::Resolv::DNS::Resource
        sig { returns(::String) }
        def data
        end
      end

      class HINFO < ::Resolv::DNS::Resource
        sig { returns(::String) }
        def cpu
        end

        sig { returns(::String) }
        def os
        end
      end

      module IN
        class A < ::Resolv::DNS::Resource
          sig { returns(::Resolv::IPv4) }
          def address
          end
        end

        class AAAA < ::Resolv::DNS::Resource
          sig { returns(::Resolv::IPv6) }
          def address
          end
        end

        class SRV < ::Resolv::DNS::Resource
          sig { returns(::Integer) }
          def port
          end

          sig { returns(::Integer) }
          def priority
          end

          sig { returns(::String) }
          def target
          end

          sig { returns(::Integer) }
          def weight
          end
        end

        class WKS < ::Resolv::DNS::Resource
          sig { returns(::Resolv::IPv4) }
          def address
          end

          sig { returns(::Integer) }
          def bitmap
          end

          sig { returns(::Integer) }
          def protocol
          end
        end
      end

      class LOC < ::Resolv::DNS::Resource
        sig { returns(::Integer) }
        def altitude
        end

        sig { returns(::Integer) }
        def hprecision
        end

        sig { returns(::Integer) }
        def latitude
        end

        sig { returns(::Integer) }
        def longitude
        end

        sig { returns(::Integer) }
        def ssize
        end

        sig { returns(::Integer) }
        def version
        end

        sig { returns(::Integer) }
        def vprecision
        end
      end

      class MINFO < ::Resolv::DNS::Resource
        sig { returns(::String) }
        def emailbx
        end

        sig { returns(::String) }
        def rmailbx
        end
      end

      class MX < ::Resolv::DNS::Resource
        sig { returns(::String) }
        def exchange
        end

        sig { returns(::Integer) }
        def preference
        end
      end

      class SOA < ::Resolv::DNS::Resource
        sig { returns(::Integer) }
        def expire
        end

        sig { returns(::Integer) }
        def minimum
        end

        sig { returns(::String) }
        def mname
        end

        sig { returns(::Integer) }
        def refresh
        end

        sig { returns(::Integer) }
        def retry
        end

        sig { returns(::String) }
        def rname
        end

        sig { returns(::Integer) }
        def serial
        end
      end

      class TXT < ::Resolv::DNS::Resource
        sig { returns(::String) }
        def data
        end

        sig { returns(::Array) }
        def strings
        end
      end
    end
  end

  class Hosts
    sig { returns(::String) }
    def getaddress(name)
    end

    sig { returns(::Array) }
    def getaddresses(name)
    end

    sig { returns(::String) }
    def getname(address)
    end

    sig { returns(::Array) }
    def getnames(address)
    end
  end

  class IPv4
    sig { returns(::String) }
    def address
    end

    sig { returns(::Integer) }
    def hash
    end

    sig { returns(::String) }
    def inspect
    end

    sig { returns(::Resolv::DNS::Name) }
    def to_name
    end

    sig { returns(::String) }
    def to_s
    end
  end

  class IPv6
    sig { returns(::String) }
    def address
    end

    sig { returns(::Integer) }
    def hash
    end

    sig { returns(::String) }
    def inspect
    end

    sig { returns(::Resolv::DNS::Name) }
    def to_name
    end

    sig { returns(::String) }
    def to_s
    end
  end

  module LOC
    class Alt
      sig { returns(::Integer) }
      def altitude
      end

      sig { returns(::Integer) }
      def hash
      end

      sig { returns(::String) }
      def inspect
      end

      sig { returns(::String) }
      def to_s
      end
    end

    class Coord
      sig { returns(::String) }
      def coordinates
      end

      sig { returns(::Integer) }
      def hash
      end

      sig { returns(::String) }
      def inspect
      end

      sig { returns(::String) }
      def to_s
      end
    end

    class Size
      sig { returns(::Integer) }
      def hash
      end

      sig { returns(::String) }
      def inspect
      end

      sig { returns(::String) }
      def scalar
      end

      sig { returns(::String) }
      def to_s
      end
    end
  end
end

class Ripper
  sig { returns(::Array) }
  def self.lex(src, filename = nil, lineno = nil, **kw)
  end

  sig { returns(::Array) }
  def self.sexp(src, filename = nil, lineno = nil, raise_errors: nil)
  end

  sig { returns(::Array) }
  def self.sexp_raw(src, filename = nil, lineno = nil, raise_errors: nil)
  end

  sig { returns(::Array) }
  def self.tokenize(src, filename = nil, lineno = nil, **kw)
  end

  class Filter
    sig { returns(::String) }
    def filename
    end

    sig { returns(::Ripper::Lexer::State) }
    def state
    end
  end

  class Lexer < ::Ripper
    sig { returns(::Array) }
    def errors
    end

    sig { returns(::Array) }
    def lex(**kw)
    end

    sig { returns(::Array) }
    def parse(raise_errors: nil)
    end

    sig { returns(::Array) }
    def scan(**kw)
    end

    sig { returns(::Array) }
    def tokenize(**kw)
    end

    private
    sig { returns(::Ripper::Lexer::Elem) }
    def _push_token(tok)
    end

    sig { returns(::Array) }
    def compile_error(mesg)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_CHAR(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on___end__(tok)
    end

    sig { returns(::Array) }
    def on_alias_error(mesg, elem)
    end

    sig { returns(::Array) }
    def on_assign_error(mesg, elem)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_backref(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_backtick(tok)
    end

    sig { returns(::Array) }
    def on_class_name_error(mesg, elem)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_comma(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_comment(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_const(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_cvar(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_embdoc(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_embdoc_beg(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_embdoc_end(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_embexpr_beg(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_embexpr_end(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_embvar(tok)
    end

    sig { returns(::Array) }
    def on_error1(mesg)
    end

    sig { returns(::Array) }
    def on_error2(mesg, elem)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_float(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_gvar(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_ident(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_ignored_nl(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_ignored_sp(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_imaginary(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_int(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_ivar(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_kw(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_label(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_label_end(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_lbrace(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_lbracket(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_lparen(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_nl(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_op(tok)
    end

    sig { returns(::Array) }
    def on_param_error(mesg, elem)
    end

    sig { returns(::Array) }
    def on_parse_error(mesg)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_period(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_qsymbols_beg(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_qwords_beg(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_rational(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_rbrace(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_rbracket(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_regexp_beg(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_regexp_end(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_rparen(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_semicolon(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_sp(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_symbeg(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_symbols_beg(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_tlambda(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_tlambeg(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_tstring_beg(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_tstring_content(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_tstring_end(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_words_beg(tok)
    end

    sig { returns(::Ripper::Lexer::Elem) }
    def on_words_sep(tok)
    end

    class Elem
      sig { returns(::Symbol) }
      def event
      end

      sig { returns(::Symbol) }
      def event=(arg1)
      end

      sig { returns(::Ripper::Lexer::State) }
      def state
      end

      sig { returns(::Ripper::Lexer::State) }
      def state=(arg1)
      end

      sig { returns(::String) }
      def tok
      end

      sig { returns(::String) }
      def tok=(arg1)
      end
    end

    class State
      sig { returns(::Ripper::Lexer::State) }
      def &(i)
      end

      sig { returns(::Integer) }
      def to_i
      end

      sig { returns(::Integer) }
      def to_int
      end

      sig { returns(::String) }
      def to_s
      end

      sig { returns(::Ripper::Lexer::State) }
      def |(i)
      end
    end
  end
end

class RubyVM
  class InstructionSequence
    sig { returns(::RubyVM::InstructionSequence) }
    def each_child(&block)
    end

    sig { returns(::String) }
    def inspect
    end

    sig { returns(::String) }
    def path
    end

    sig { returns(::Array) }
    def to_a
    end
  end
end

class Set
  include ::Enumerable

  sig { returns(::Set) }
  def self.[](*ary)
  end

  sig { params(block: T.proc.void).returns(::Hash) }
  def classify(&block)
  end

  sig { params(func: T.proc.void).returns(::Set) }
  def divide(&func)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def each(&block)
  end

  sig { returns(::Set) }
  def flatten
  end

  sig { returns(::Integer) }
  def length
  end

  sig { returns(::Integer) }
  def size
  end

  sig { returns(::Array) }
  def to_a
  end
end

module Shellwords
  sig { returns(::String) }
  def self.escape(str)
  end

  sig { returns(::String) }
  def self.join(array)
  end

  sig { returns(::String) }
  def self.shellescape(str)
  end

  sig { returns(::String) }
  def self.shelljoin(array)
  end

  sig { returns(::Array) }
  def self.shellsplit(line)
  end

  sig { returns(::Array) }
  def self.shellwords(line)
  end

  sig { returns(::Array) }
  def self.split(line)
  end

  private
  sig { returns(::String) }
  def shellescape(str)
  end

  sig { returns(::String) }
  def shelljoin(array)
  end

  sig { returns(::Array) }
  def shellsplit(line)
  end

  sig { returns(::Array) }
  def shellwords(line)
  end
end

class Socket < ::BasicSocket
  sig { params(block: NilClass).returns(::Array) }
  def self.tcp_server_sockets(host = nil, port, &block)
  end

  sig { params(block: NilClass).returns(::Socket) }
  def self.unix_server_socket(path, &block)
  end

  class UDPSource
    sig { returns(::String) }
    def inspect
    end

    sig { returns(::Addrinfo) }
    def local_address
    end

    sig { returns(::Addrinfo) }
    def remote_address
    end
  end
end

class String
  include ::Comparable
  include ::JSON::Ext::Generator::GeneratorMethods::String

  sig { returns(::String) }
  def self.new(*args)
  end

  sig { returns(::String) }
  def dump
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def each_byte(&block)
  end

  sig { returns(::Integer) }
  def hex
  end

  sig { returns(::String) }
  def shellescape
  end

  sig { returns(::Array) }
  def shellsplit
  end
end

class Struct
  include ::Enumerable

  sig { params(block: NilClass).returns(::Enumerator) }
  def each_pair(&block)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  sig { params(block: T.proc.void).returns(::Array) }
  def filter(&block)
  end

  sig { returns(::Integer) }
  def hash
  end

  sig { returns(::String) }
  def inspect
  end

  sig { returns(::Integer) }
  def length
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  sig { params(block: T.proc.void).returns(::Array) }
  def select(&block)
  end

  sig { returns(::Integer) }
  def size
  end

  sig { returns(::String) }
  def to_s
  end

  sig { returns(::Array) }
  def values
  end

  sig { returns(::Array) }
  def values_at(integer_range = nil, *integers)
  end
end

class Symbol
  include ::Comparable

  sig { returns(::Symbol) }
  def capitalize(*options)
  end

  sig { returns(::String) }
  def inspect
  end

  sig { returns(::Symbol) }
  def next
  end

  sig { returns(::Integer) }
  def size
  end

  sig { returns(::Symbol) }
  def succ
  end
end

module TSort
  sig { params(block: NilClass).returns(::Enumerator) }
  def self.each_strongly_connected_component(each_node, each_child, &block)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def self.each_strongly_connected_component_from(node, each_child, id_map = nil, stack = nil, &block)
  end

  sig { returns(::Array) }
  def self.strongly_connected_components(each_node, each_child)
  end

  sig { returns(::Array) }
  def self.tsort(each_node, each_child)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def self.tsort_each(each_node, each_child, &block)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def each_strongly_connected_component(&block)
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def each_strongly_connected_component_from(node, id_map = nil, stack = nil, &block)
  end

  sig { returns(::Array) }
  def strongly_connected_components
  end

  sig { returns(::Array) }
  def tsort
  end

  sig { params(block: NilClass).returns(::Enumerator) }
  def tsort_each(&block)
  end
end

class Tempfile
  sig { params(block: NilClass).returns(::File) }
  def self.create(basename = nil, tmpdir = nil, mode: nil, anonymous: nil, **options, &block)
  end

  sig { params(block: NilClass).returns(::Tempfile) }
  def self.open(*args, **kw, &block)
  end

  sig { returns(::String) }
  def inspect
  end

  sig { returns(::Integer) }
  def length
  end

  sig { returns(::File) }
  def open
  end

  sig { returns(::Integer) }
  def size
  end
end

class Thread
  sig { returns(::Array) }
  def keys
  end

  sig { returns(::Thread) }
  def run
  end

  class Backtrace
    class Location
      sig { returns(::Integer) }
      def lineno
      end
    end
  end

  class Queue
    sig { returns(::Integer) }
    def length
    end

    sig { returns(::Integer) }
    def size
    end
  end
end

class Time
  include ::Comparable

  sig { returns(::Time) }
  def self.httpdate(date)
  end

  sig { returns(::Time) }
  def self.iso8601(time)
  end

  sig { returns(::Time) }
  def self.parse(date, now = nil, &block)
  end

  sig { returns(::Time) }
  def self.rfc2822(date)
  end

  sig { returns(::Time) }
  def self.rfc822(date)
  end

  sig { returns(::Time) }
  def self.strptime(date, format, now = nil, &block)
  end

  sig { returns(::Time) }
  def self.xmlschema(time)
  end

  sig { returns(::Integer) }
  def self.zone_offset(zone, year = nil)
  end

  sig { returns(::Integer) }
  def hash
  end

  sig { returns(::String) }
  def httpdate
  end

  sig { returns(::String) }
  def inspect
  end

  sig { returns(::String) }
  def rfc2822
  end

  sig { returns(::String) }
  def rfc822
  end

  sig { returns(::String) }
  def xmlschema(fraction_digits = 0)
  end
end

module URI
  sig { returns(::Array) }
  def self.decode_www_form(str, enc = nil, separator: nil, use__charset_: nil, isindex: nil)
  end

  sig { returns(::String) }
  def self.decode_www_form_component(str, enc = nil)
  end

  sig { returns(::String) }
  def self.encode_www_form(enum, enc = nil)
  end

  sig { returns(::String) }
  def self.encode_www_form_component(str, enc = nil)
  end

  sig { params(block: NilClass).returns(::Array) }
  def self.extract(str, schemes = nil, &block)
  end

  sig { returns(::Regexp) }
  def self.regexp(schemes = nil)
  end

  sig { returns(::Hash) }
  def self.scheme_list
  end

  class File < ::URI::Generic
    sig { returns(::URI::File) }
    def self.build(args)
    end

    sig { returns(::String) }
    def set_host(v)
    end
  end

  class Generic
    include ::URI

    sig { returns(::Array) }
    def self.component
    end

    sig { returns(::Array) }
    def coerce(oth)
    end

    sig { returns(::Array) }
    def component
    end

    sig { returns(::Integer) }
    def hash
    end

    sig { returns(::String) }
    def inspect
    end

    sig { returns(::String) }
    def merge!(oth)
    end

    sig { returns(::Array) }
    def select(*components)
    end

    sig { returns(::String) }
    def to_s
    end

    protected
    sig { returns(::Array) }
    def component_ary
    end

    private
    sig { returns(::String) }
    def escape_userpass(v)
    end

    sig { returns(::String) }
    def merge_path(base, rel)
    end

    sig { returns(::Array) }
    def route_from0(oth)
    end

    sig { returns(::String) }
    def route_from_path(src, dst)
    end

    sig { returns(::Array) }
    def split_path(path)
    end

    sig { returns(::Array) }
    def split_userinfo(ui)
    end
  end

  class HTTP < ::URI::Generic
    include ::OpenURI::OpenRead

    sig { returns(::String) }
    def authority
    end

    sig { returns(::String) }
    def origin
    end

    sig { returns(::String) }
    def request_uri
    end
  end

  class LDAP < ::URI::Generic
    sig { returns(::String) }
    def attributes
    end

    sig { returns(::String) }
    def attributes=(val)
    end

    sig { returns(::String) }
    def dn
    end

    sig { returns(::String) }
    def dn=(val)
    end

    sig { returns(::String) }
    def extensions=(val)
    end

    sig { returns(::String) }
    def filter
    end

    sig { returns(::String) }
    def filter=(val)
    end

    sig { returns(::FalseClass) }
    def hierarchical?
    end

    sig { returns(::String) }
    def scope
    end

    sig { returns(::String) }
    def scope=(val)
    end

    protected
    sig { returns(::String) }
    def set_attributes(val)
    end

    sig { returns(::String) }
    def set_dn(val)
    end

    sig { returns(::String) }
    def set_extensions(val)
    end

    sig { returns(::String) }
    def set_filter(val)
    end

    sig { returns(::String) }
    def set_scope(val)
    end

    private
    sig { returns(::String) }
    def build_path_query
    end
  end

  class MailTo < ::URI::Generic
    include ::URI::RFC2396_REGEXP

    sig { returns(::Array) }
    def headers
    end

    sig { returns(::String) }
    def headers=(v)
    end

    sig { returns(::String) }
    def to
    end

    sig { returns(::String) }
    def to=(v)
    end

    sig { returns(::String) }
    def to_mailtext
    end

    sig { returns(::String) }
    def to_rfc822text
    end
  end

  class RFC2396_Parser
    include ::URI::RFC2396_REGEXP

    sig { returns(::String) }
    def escape(str, unsafe = nil)
    end

    sig { params(block: NilClass).returns(::Array) }
    def extract(str, schemes = nil, &block)
    end

    sig { returns(::Regexp) }
    def make_regexp(schemes = nil)
    end

    sig { returns(::Hash) }
    def pattern
    end

    sig { returns(::Hash) }
    def regexp
    end

    sig { returns(::String) }
    def unescape(str, escaped = nil)
    end
  end
end

class UnboundMethod
  sig { returns(::Integer) }
  def hash
  end

  sig { returns(::String) }
  def inspect
  end

  sig { returns(::Symbol) }
  def original_name
  end

  sig { returns(::String) }
  def to_s
  end
end

class UncaughtThrowError < ::ArgumentError
  sig { returns(::String) }
  def to_s
  end
end
