//! Files a generator wrote: a `--dead` row in one says so (DEC-403).
//!
//! Generated code implements a contract its runtime calls generically — a
//! GraphQL client's `Query.from_response!`, a protobuf message's accessors —
//! so no call site names the method, and deleting it is undone the next time
//! the code is generated. Marked as `linguist-generated` in `.gitattributes`,
//! by a `generated/` directory, or by a header comment saying so.

use std::collections::{BTreeSet, HashMap};
use std::io::Write;
use std::path::Path;
use std::process::{Command, Stdio};

/// How many lines a header is looked for in: past a magic comment or two.
const HEADER_LINES: usize = 5;

#[derive(Default)]
pub(super) struct Generated {
    /// Each generated file (relative to the checkout), and what says so.
    files: HashMap<String, String>,
}

impl Generated {
    /// Which of `paths` in the checkout at `root` are generated.
    pub(super) fn read<'a>(root: &Path, paths: impl Iterator<Item = &'a str>) -> Generated {
        let paths: BTreeSet<&str> = paths.collect();
        let marked = linguist_generated(root, &paths);
        let files = paths
            .into_iter()
            .filter_map(|path| {
                let why = if marked.contains(path) {
                    "`.gitattributes` marks it `linguist-generated`".to_string()
                } else if path.split('/').rev().skip(1).any(|dir| dir == "generated") {
                    "a `generated/` directory".to_string()
                } else {
                    let text = std::fs::read_to_string(root.join(path)).ok()?;
                    let line = text
                        .lines()
                        .take(HEADER_LINES)
                        .find(|l| says_generated(l))?;
                    format!("its header: `{}`", line.trim())
                };
                Some((path.to_string(), why))
            })
            .collect();
        Generated { files }
    }

    /// Why `path` is generated code, if it is.
    pub(super) fn why(&self, path: &str) -> Option<&str> {
        self.files.get(path).map(String::as_str)
    }
}

/// The paths git's attributes mark `linguist-generated`, asked in one batch.
fn linguist_generated(root: &Path, paths: &BTreeSet<&str>) -> BTreeSet<String> {
    let child = Command::new("git")
        .arg("-C")
        .arg(root)
        .args(["check-attr", "--stdin", "-z", "linguist-generated"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn();
    let Ok(mut child) = child else {
        return BTreeSet::new();
    };
    // Written from a thread of its own: git answers as it reads, and a full
    // stdout pipe would otherwise stall both ends.
    let input: Vec<u8> = paths
        .iter()
        .flat_map(|p| [p.as_bytes(), b"\0"].concat())
        .collect();
    let writer = child.stdin.take().map(|mut stdin| {
        std::thread::spawn(move || {
            let _ = stdin.write_all(&input);
        })
    });
    let out = child.wait_with_output();
    if let Some(writer) = writer {
        let _ = writer.join();
    }
    let Ok(out) = out else {
        return BTreeSet::new();
    };
    // `path NUL attribute NUL value NUL`, per path.
    let fields: Vec<&[u8]> = out.stdout.split(|b| *b == 0).collect();
    fields
        .chunks(3)
        .filter(|f| f.len() == 3 && matches!(f[2], b"set" | b"true"))
        .map(|f| String::from_utf8_lossy(f[0]).into_owned())
        .collect()
}

/// A comment that says its file is generated: "DO NOT EDIT" or
/// `@generated` anywhere in it, or one that opens "Generated by", "This file
/// is (auto-)generated". Not "generated by" mid-sentence — "the token is
/// generated by SecureRandom" — nor a class name that holds the word.
fn says_generated(line: &str) -> bool {
    let Some(comment) = line.trim_start().strip_prefix('#') else {
        return false;
    };
    let comment = comment.trim().to_ascii_lowercase();
    comment.contains("do not edit")
        || comment.contains("@generated")
        || [
            "generated by",
            "auto-generated",
            "autogenerated",
            "code generated",
            "this file is generated",
            "this file is auto-generated",
            "this file was generated",
            "this file was auto-generated",
        ]
        .iter()
        .any(|opening| comment.starts_with(opening))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_header_comment_says_generated_and_a_sentence_does_not() {
        assert!(says_generated(
            "# Generated by the protocol buffer compiler.  DO NOT EDIT!"
        ));
        assert!(says_generated(
            "# This file is auto-generated from the schema."
        ));
        assert!(says_generated("  # @generated"));
        assert!(!says_generated("# The token is generated by SecureRandom."));
        assert!(!says_generated(
            "class AddIsAutoGeneratedToEmails < Migration # generated"
        ));
    }
}
